### ISSUE TITLE
イベントページ(doorkeeper)公開

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#1]

**Comment by PharaohKJ** [comment]
```
少なくともDoorkeeperでやった場合は「個人情報はAWSに提供する」の記述が必須で、他のスポンサーについても参加者情報を提供するかどうかを決めて事前にスポンサーに伝えることが必須
```

とのことで、これを明記すること！今の所、共催スポンサーのAWSさまとJAWS-UG金沢で、名簿情報は共有するが、他スポンサーさまへはお渡ししない予定。そのつもりでスポンサー様説明文書明記。

**Comment by PharaohKJ** [comment]
写真・SNSのNGを申込時に事前質問すること
AWS側との共催につき、その文言を頂く予定(2019-09-11うちあわせより)
割り勘飲み会に参加するかどうか事前質問すること

**Comment by PharaohKJ** [comment]
次これ目標でやります。

2019-10 最初の週中に公開予定。AWSさん側から提示のプライバシーポリシーについては、公式slack #community-day-2019 で提供あり。

**Comment by PharaohKJ** [comment]
現在、作成しました。非公開状態にしてあります。
UG金沢公式slack #general と 全国UG slack #community-day-2019 にスクショ・申込時質問など添付したのでレビューをお願いします。

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday 

事前アンケートについてAWSさんから「こういう項目を事前に集めたい」と打診がありました。
( 公式slackの #community-day-2019 より )
詳細はUG金沢 slack #general に置きましたのでレビューお願いします。

加藤の見解としては、ドアキにこれが保存されちゃうから扱いが大事になるよね、ぐらいだろうのでOKかなと考えています。どうでしょ？

**Comment by TAKAyukiatkwsk** [comment]
事前アンケート、問題ないかなと思います。

**Comment by PharaohKJ** [comment]
事前アンケート追加しました。10/17中にレビューしてください。10/18公開予定です。
詳細はslackにはりました。

@jaws-ug-kanazawa/communityday
