### ISSUE TITLE
会計部設置

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#10]
- 出金・入金記録担当者選出
- 記録簿作成
    - 立て替え払い一覧
    - 精算状況

**Comment by PharaohKJ** [comment]
現状の本会は Google Spread Sheet を使っています。
実際のところ、現金がそのまま本会から出ていくことはないと考えていますので、
入金・出金・建て替え日時・用途・担当者
がわかる申請書 & 記録ができればよいと考えています。

その連絡フォーマット & 連絡場所 & オープンな記載場所 を wiki に記入したらクローズ

**Comment by TAKAyukiatkwsk** [comment]
@PharaohKJ 叩きを考えてみました。

申請: Google Form
記録: Google Spreadsheet (上記フォームにひもづいたもの)

想定されるフロー

- 立て替えがあるスタッフはGoogle Formで入力し申請
- 申請されるとSpreadsheetに入力内容が記録される
  - 申請されたイベントをJAWS-UG kanazawa Slackに通知できると良さそう(実装できるかは未検証)
- 精算が完了したら、会計スタッフがSpreadsheet上で精算完了の旨を記録する

足りない部分や想定と違う部分あるとおもうので、レビューお願いしますー。

**Comment by PharaohKJ** [comment]
OKじゃないでしょうか。
今回は入金もある予定なので、そのタイミングなども記録・管理できるようにしてください。
[現金出納帳](https://www.timakai.com/home/atoz_genkin_suitou) で本来はいいんですが、どうしても「建て替え」がでちゃうんで現金出納帳 + 建て替え管理簿、でよいかと。
現金出納帳の
入金はスポンサーさんからの入金という項目のみで増えていき、
出金は「建て替え管理簿の○○について建て替え払い」という項目のみで増えていく
ってことになりそうかな？

よろしくです。

**Comment by TAKAyukiatkwsk** [comment]
ありがとうございます。リンクの内容で現金出納帳 + 立て替え管理簿イメージできました。

サンプルで作ってみたので、認識あってるか確認おねがいしたいです。

入金出金申請フォーム
https://forms.gle/QKEAwREKrQQ6LxCN6
立て替え申請フォーム
https://forms.gle/FwdFEZ7pUcrL9GxC9
記録&管理用スプレッドシート
https://docs.google.com/spreadsheets/d/1n_JBkcWxdkWprVJTmuT7zdF6CXGinljlZHX7XuUv0hY/edit?usp=sharing

**Comment by PharaohKJ** [comment]
いいと思います。
入金出金は建て替え払い申請フォームをもとに @TAKAyukiatkwsk が書けばいいと思いますのでフォームまではいらないかなあ、ご自身で使われる分にはOKかと。

フォーム立て替え払いの日付のところを「実際に業者などに支払った日を記入してください」などコメントいれておいてほしいですー。

入金出金記録のところに対応する建て替え払い申請書の行番号を書くようにしてください。専用カラムがあったほうがいいかも。

**Comment by matyuda** [comment]
@TAKAyukiatkwsk さんありがとうございます。
入出金に関する領収書の取り扱いはどのようにされますか？

入金・・・「AWS Community Day」の領収書を発行する
出金・・・領収書のあて名書きは「AWS Community Day」としてもらう等。

**Comment by matyuda** [comment]
@TAKAyukiatkwsk さん
サンプル立て替え申請フォームに１件サンプルとして入力してみました。
金額のカラムは、金額（税込）としていただいた方がよいと思います。

**Comment by PharaohKJ** [comment]
領収書の宛名についてはAWSさんと相談します。
あ、領収書の原本の保管についても説明要りますね。お待ちを。

-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pxw_kato / twitter: PhalanXware

**Comment by TAKAyukiatkwsk** [comment]
@PharaohKJ @matyuda 
アドバイスありがとうございます。以下について反映しました。入金出金フォームは自分用にしておきますね。
https://github.com/jaws-ug-kanazawa/aws-community-day/issues/10#issuecomment-524153035
https://github.com/jaws-ug-kanazawa/aws-community-day/issues/10#issuecomment-525092683

> 領収書の宛名についてはAWSさんと相談します。
あ、領収書の原本の保管についても説明要りますね。お待ちを。

確認よろしくお願いします 🙇

**Comment by PharaohKJ** [comment]
> はい、宛先は担当者で大丈夫です。原本はいらず、PDFで大丈夫です。


とのことなので、

1. 領収書は各自の名前で。
2. 領収書のPdFをなんとかして送る(slack ? 申請フォーム？

としてルール決めお願いしますー。
-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pxw_kato / twitter: PhalanXware

**Comment by TAKAyukiatkwsk** [comment]
申請フォームに領収書をアップロードする項目を追加しました。

**Comment by PharaohKJ** [comment]
申請フォーム確認しました。
添付先のドライブは @TAKAyukiatkwsk さんじゃないとダウンロードできないようになってるのかな？
それでもいいかな？ただ、スポンサーに一式全部提出しなくてはいけないかもしれないので、そのときはお願いします。

だいたい完成したと思うので [Home · jaws-ug-kanazawa/aws-community-day Wiki](https://github.com/jaws-ug-kanazawa/aws-community-day/wiki#%E7%AB%8B%E3%81%A6%E6%9B%BF%E3%81%88%E6%89%95%E3%81%84%E7%94%B3%E8%AB%8B) にフォームのURLなど書き込んで本 issue をクローズしてください

**Comment by PharaohKJ** [comment]
↑URL書き込んでおいたんで、URLがあってるか確認したらクローズしてください

**Comment by TAKAyukiatkwsk** [comment]
wikiの更新ありがとうございます！PDF添付先のドライブも共有してwikiに貼っておきました。(サンプルではなく本番用のURLに差し替えてあります。)
