### ISSUE TITLE
スポンサー・協賛・協力探し

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#12]
- スポンサーに求める要件とそのお返しの決定
    - 会場費スポンサー
    - ドリンクスポンサー
    - 懇親会費スポンサー
    - 登壇協力
    - ハンズオン貸出機
    - ロゴ記載など
- スポンサー・協力探し
    - 声がけ先一覧の作成
    - 声がけ担当の決定
    - 当日配布物など受け取り
        - 担当者決定
        - 事前配送先決定

**Comment by PharaohKJ** [comment]
- [x] ジョブボード設置可能かをAWSJと相談する。

**Comment by matyuda** [comment]
Slackより転記しておきます。(※メンション名を変更しています)
from @pharaohkj
>@matyuda さん、運営協力・登壇ならジョブボードOKでいきます。 @channel かくい、いちおう、沼口さんOKなんで、それスポンサー向け資料に書いておきます。

@pharaohkjありがとうございます。
登壇いただく条件でジョブボードokなら登壇する側のインセンティブにもなりますし、聞いている側も何故ここに募集があるのかも話が繋がりやすいと思います。また、仕事を探しに来た人が気になる企業のセッションを聞く動機にもなりますので、非常に良いと思います。

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday 各位

スポンサー募集前半の文章はおいといて、協賛方法一覧とそのリワードについて文章おこしてみました。レビューお願いします。

https://paper.dropbox.com/doc/--Ajh7sD_xopBURSB~tEB2mjb8Ag-RiMyMAijPmiulzeyeO0Wq#:uid=675903740065089163084406&h2=%E3%81%94%E5%8D%94%E5%8A%9B%E3%81%84%E3%81%9F%E3%81%A0%E3%81%8D%E3%81%9F%E3%81%84%E3%81%93%E3%81%A8

**Comment by higachan0406** [comment]
「します。」「しましょう。」で統一されていない箇所が2つ気になりました。
タイトル「狙い」の以下２つ。
「IT」「クラウド」と言っただけで「俺とは関係ない」「すごいむずかしそう」というイメージがあるが、そんなことはない！北陸にクラウド(AWS)は関係ある！自分のビジネス・仕事を強力に推進するチカラになる！という話をし、みんなで考えることができるようにする。

巨大なインフラ、アジャイル開発、プロトタイプ開発、小企業、個人のやってみた、スモールスタートなど、相性もよいということを認知させたい。

**Comment by PharaohKJ** [comment]
すみませぬ、前半はちょっとおいといてください。前半できたらまた連絡します！後半の協賛方法一覧とそのリワードについてレビューをお願いします。

**Comment by matyuda** [comment]
私は内容確認しましたが、内容に問題はないと思います。

**Comment by TAKAyukiatkwsk** [comment]
@PharaohKJ 
> 勉強会において、御社の分野とその地元・活用事例としての登壇を募集しております。

[IMO] 「分野とその地元」というのがすこし分かりにくいなと感じました。
なんとなく以下の2つのテーマ？に関することを登壇して欲しいのかなと感じたのですが理解あってますでしょうか？

* 御社の事業分野におけるAWS活用事例
* 御社の地元におけるAWS活用事例

その他の部分はLGTMです！！

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday 

いったん、清書第一弾としまして、wikiにもリンク貼っておきました。
レビューよろしくおねがいします。

https://paper.dropbox.com/doc/--Aj0j4SU52blOV2EqxQVL~IK_AQ-RiMyMAijPmiulzeyeO0Wq

**Comment by PharaohKJ** [comment]
@aibax さんが声かけリスト作成中ってことで、担当を変更。

**Comment by aibax** [comment]
一旦 Google Spreadsheet に転記して作成。追記しながら順次整理していく。
https://docs.google.com/spreadsheets/d/12GxEBJuL2my9iDPWs-JmgCqTvCT12RF7lGA7FaB0lgE/edit?usp=sharing

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday 各位↑に自社名かいてね！！！担当者はご自身の名前か、他にヘルプにきてほしい人の名前書いておいてください！

**Comment by PharaohKJ** [comment]
https://forms.gle/GuGEZu9dTyb3L1mMA

ロゴファイル登録用フォーム作りました。続けて登壇応募フォーム作ります。

**Comment by PharaohKJ** [comment]
応募フォームつくりました。短縮URLもつくりました。

wiki にURL貼っておきましたが、企業様向け企画書にも貼り付けておきます。

**Comment by PharaohKJ** [comment]
https://paper.dropbox.com/doc/--AlRNR6i7CXhbCnsoJ~XPFOSvAg-RiMyMAijPmiulzeyeO0Wq#:uid=082737545312939111859649&h2=%E5%8D%94%E8%B3%9B%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B5%E3%83%BC%E3%81%95%E3%81%BE%E3%81%B8

https://github.com/jaws-ug-kanazawa/aws-community-day/wiki#aws-community-day-金沢-2019-準備会-wiki

に記載済み

**Comment by PharaohKJ** [comment]
とりあえず私が声かけやすいところはかけました。

担当決まってないところ、真面目に担当決めましょう。目標は10月第一週中。

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday 

https://docs.google.com/spreadsheets/d/12GxEBJuL2my9iDPWs-JmgCqTvCT12RF7lGA7FaB0lgE/edit?usp=sharing

の担当あいてるところ、誰か手伝っていただけませんか？

**Comment by PharaohKJ** [comment]
先方から質問がきたので、資料にFAQを追加して書き込んでおきました。

https://paper.dropbox.com/doc/--AluRnZ~3rJzLFh3jziQkq3koAQ-RiMyMAijPmiulzeyeO0Wq

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday ↑どうでしょう？土曜のJAWS-UG金沢終わって日曜までに埋まらなかったら加藤が手配してお願いします・・・。すみませんが手伝ってください。

**Comment by PharaohKJ** [comment]
もうたぶんこれ以上でないんでいったんここでクローズ。ご協力ありがとうございました。
