### ISSUE TITLE
当日タスク

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#13]
- 当日タスク一覧の作成
- 当日企画一覧の作成
- サポートスタッフの割り当て
- 運営本部設置
- 講師控え室設置
- 受付設置
    - 担当ローテ表
- スポンサー受付設置
    - 担当ローテ表
- 各部屋進担当決定
    - 司会進行 + プロジェクター補助
    - ハンズオンサポート

**Comment by PharaohKJ** [comment]
[人員希望&配置シート](https://docs.google.com/spreadsheets/d/1iHnHPjI5lwrue9aFlhEGsJgTQ8duKn-OTI4VvdSKBgM/edit?usp=sharing)

を作成しました。人手がほしい人はここに記入してください。

**Comment by PharaohKJ** [comment]
↑ @jaws-ug-kanazawa/communityday

**Comment by PharaohKJ** [comment]
↑ @jaws-ug-kanazawa/communityday 当日ここ俺やるよ！ってのは名前記入してください。

**Comment by TAKAyukiatkwsk** [comment]
ハンズオンに関して人員希望を記入しました。参加者へのサポート3人としましたがどう思いますか？

**Comment by PharaohKJ** [comment]
ハンズオン参加者の人数によってはいるかもね・・・。AWSのかた1+スタッフ1で、2人が最低かな？

ドアキの最初のアンケートで「ハンズオン参加を希望されますか？」を追加して人数予想がつくようにしておきます。

いったん3にしておきましょう。

**Comment by matyuda** [comment]
下記お願いします
- [ ] 登壇者席と配信用スペースを用意

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday 各位
https://docs.google.com/spreadsheets/d/1iHnHPjI5lwrue9aFlhEGsJgTQ8duKn-OTI4VvdSKBgM/edit?usp=sharing

の配置シートを参照 & 編集してください。

適当に加藤が名前書きましたが、変更とか自分の名前記入してください！
特に自分がききたいトラックの司会をやってくれると助かります！

**Comment by INTEC-Takayasu** [comment]
インテックから各会場１人ずつスタッフを出します。個人名はまだ確定しておりませんので、とりあえず「インテック１～３」と書かせていただきました。当日でも構わないので、具体的に何をすればよいか打ち合わせさせてください。
また、セッティングや後片付けは、その場にいる社員たちで手伝います。５名ぐらいは確保できます。

**Comment by PharaohKJ** [comment]
@INTEC-Takayasu さん、めっっっっっっっっっっっっっっっっっちゃ助かりました。本当にありがとうございました！

**Comment by INTEC-Takayasu** [comment]
@PharaohKJ こちらこそ、どうもありがとうございました！参加した社員もとても良い刺激を受けました。北陸でAWSを広めていきたいと思いますので、どうかよろしくお願いいたします！！
