### ISSUE TITLE
非公式飲み会(うちあげ)手配

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#14]
- お店決定
- 予算決定
- 予約

**Comment by higachan0406** [comment]
[メモ]
>20時 非公式打ち上げ飲み会

・時間は20時より。
・料理は香箱蟹があること。
・人数は100?
・11/20の曜日は、水曜日。よって、金曜の飲みのノリでなく、
　少し金沢の美味しいものを食べる人、次の日を意識して
　早めに変える北陸民(石川、富山、福井)を意識する。

[確認]
・人数100人て、どこかのホテルの会場がよい？
　それとも、居酒屋で30人、30人、40人で分ける？

[お店候補]
・底曳き割烹　もんぜん
　ここは去年だったか、沼口さんもいらっしゃったところで、
　私は県外の方ならおすすめして食べていただきたい香箱蟹を出してくれるお店と
　思いました。
　ただ、沼口さんは別の所希望されるかもですね。
　場所は金沢駅付近なので交通は良い感じ。バスもあるみたいですが、来てくれるかな？
　
・五郎八
　魚介は美味しかったのを覚えています。日本酒、手取川も美味しかった。
　ただ、片町なので武蔵から遠く。お店も小さめだったと思います。

・はす家
　ちょっとお店小さい？
　金沢駅を経由して帰る方が多いならちょうどよい？

　香箱蟹で調べてたら加藤さんの治部煮のインスタが。
　はす家 金沢駅前店 / 本町 (金沢駅から徒歩5分)
　https://rtrp.jp/articles/72964/?page=4

**Comment by higachan0406** [comment]
予算のタネになること書き忘れました。

底曳き割烹　もんぜんだと、5,000円、6,000円ぐらいなんすかね。
前、どのくらいのコースで香箱蟹、たしか治部煮もありましたよね？
が出たかどなたか知りませんか？

底曳き割烹　もんぜん　コース料理料金表
http://monzen-noto.com/monzen/monzen-enkai/

**Comment by PharaohKJ** [comment]
もんぜんは名店。前、OpsJAWSのときにいったかな？

ここの懇親会はいったん名前をかえて、非公式飲み会、としましょう。
17時から行われる公式懇親会を懇親会で。そっちは #15 で進めましょう。

タイトルを変更します。

**Comment by PharaohKJ** [comment]
あ、あとこっちはすみません、割り勘になります！予算つきません！

**Comment by higachan0406** [comment]
割り勘、了解しました。
遠方の方も割り勘、ということで。

ただ、人数感は知っておきたいところですが、
そんな気にしなくてもいいですかね？

いつも加藤さんがやってる、発表会終わりに飲みに行ける人挙手！システムで
やっちゃう感じ？

もし人数が把握できてるなら場所は抑えられます。
1日前、1週間前とかは無理だろうな〜。

**Comment by PharaohKJ** [comment]
ドアキーパーの申込時にアンケート + 1週間前に最終確認メールをドアキから出す、というようにしましょう。（いまのところ、ドアキを使う予定になっていますが、かわったらまた考えましょう）

**Comment by PharaohKJ** [comment]
@higachan0406 さん
いまのところ20弱なので、いったん25でどこか仮予約してもらえますか？
予算は5000円程度としてありますが、6,000円ぐらいまではいっても許されるかなあ・・・。

**Comment by higachan0406** [comment]
11/6、明日からカニ解禁みたいです。
明日以降、ホームページで香箱蟹をコンテンツに載せるお店が出てくると思います。

**Comment by PharaohKJ** [comment]
@higachan0406 さん
カニマジ楽しみいいいいいい。とりあえず25で予約お願いします！

**Comment by higachan0406** [comment]
@PharaohKJ 
活きな魚 地酒 座吟
https://r.gnavi.co.jp/sr2u2pph0000/menu1/?sc_lid=r-sub_news

電話：050-3374-0769

キャパ：50人
　　　　今の所空きあり。(20191106)

場所：金沢駅近い

料金：料理のみ5,000円　飲み放題2,000円　＝　7,000円

電話で聞いてみました。
ホームページで香箱蟹のコンテンツ出てないの不安だけど、
待ってたら席なくなりそう。
7,000円でよい？

**Comment by higachan0406** [comment]
底曳き割烹　もんぜん
http://monzen-noto.com/monzen/

・時間はスタートなら20:00 - 20:30なら開いてる。
    17:30から宴会があるそうで、それ終わり、片付けで入れる。
・コース5,000円＋香箱蟹単品(千円台)　＝　7,000円
　※飲み放題は入っている、ハズ。ここにするなら再度確認要。

他のお店でも、コース＊＋香箱蟹単品ていう提供が多そう。
カニづくしコースは1万円(飲み放題なし)だそうです。

**Comment by higachan0406** [comment]
地もの魚と旨い酒 とと屋

20日は団体がいるそうでNG。
香箱蟹は扱っているようです。
香箱蟹は明日解禁と話していました。

**Comment by higachan0406** [comment]
せん
http://www.1000.ne.jp/ekimae/shop.html

席は空いてます。
コースは香箱蟹入、飲み放題入で1万。
低めのコースに香箱蟹追加もやってないそうです。

**Comment by PharaohKJ** [comment]
@higachan0406 さん
もんぜんさんの5000円コースを

- 飲み放題つきですか？
- 当日、カニ食べたい！人だけ別注できますか？

を確認して、OKなら抑えてほしいです。

**Comment by PharaohKJ** [comment]
@higachan0406 さんから
場所：もんぜん
時間：20:15
送迎：なし
飲み放題：あり
カニ：なし、食べたい人は別注で。1週間前までに数はほしい
予算：＠5,000円

**Comment by higachan0406** [comment]
コースは4,000円はありませんでした。こちらのお店は5,000円からですのでご了承ください。
1週間前の11/13(水)には最終人数と、香箱蟹食べる人数を報告する必要があります。
現在25名で予約しています。
このタイミングだと、4,5人の増減は対応可能です。(5人は増えても大丈夫。)
直近の人数調整は1,2名なら可能となります。
前日の15:00まで受け付けます。

蟹甲羅焼きグラタンがメニューにあるっていってたのと、料金からみて
以下のコースになると思われます。
11月【見附島コース】90分飲み放題付全9品5000円
https://r.gnavi.co.jp/r041201/menu1/
今度電話かけたときに確認したいと思います。

**Comment by higachan0406** [comment]
予約は「ひがしかわ」で取ってあります。
団体名を聞かれましたので「AWS Community Day」とお伝えしましたので、そちらでも入れると
思います。
口頭でお伝えしましたので「AWS　コミュニティ　デイ」「エーダブルエス　コミュニティ　デイ」のような形で入り口に団体名が書かれている場合があります。

**Comment by PharaohKJ** [comment]
ありがとう！！！
人数確定を待ちましょう。

**Comment by PharaohKJ** [comment]
フォーム > https://forms.gle/kKPcA19NKPCEfkcf6
回答 > https://docs.google.com/spreadsheets/d/1IaXgzThvtnG80_rwoSvYd44jh56zvRjibdOBDKb0q8Y/edit?usp=sharing
でカニききます。11/13(水) のお昼頃締め切りとします。

**Comment by higachan0406** [comment]
先程、人数24、カニ5で予約。
前日15:00までキャンセルを受け付けます。

**Comment by PharaohKJ** [comment]
ありがとうございます！
-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pharaohkj / twitter: PhalanXware

**Comment by higachan0406** [comment]
@PharaohKJ さん
当日参加する方から食事が始まる前にお金を回収します。
参加予定のお名前のリストが欲しいです。
理由は、お金を回収した人のチェックリストを作成するためです。

**Comment by PharaohKJ** [comment]
わかりました。ロジスティクス部表にも追加しておきます。懇親会終了後、片付け中に集金をお願いします！
イベント用使い捨てリストバンドを持っていくので、集金した方に腕に巻いてもらってください。
もんぜん入り口で、これをしてない人は入場不可という運用で！
お金管理と名簿管理と受付同時にやるのは大変なので、あと2人にヘルプしてもらってください。
この手配についても、当日のタスク表に書いておきます。

**Comment by higachan0406** [comment]
11/18 打ち合わせメモ
・みなし30人で予約。
　→27人で予約。当日、3人増えた場合、入れるか確認。
・カニは６。
・集金は、受付で飲みのお金を集金を予定。
　受け取った場合は、加藤さんの使い捨て腕輪を渡すこと。
・集金したお金は、控室(扉は鍵付きであることを確認する。)。

後、お願いです。
・後、カニ食べてるの横で見てて食べたくなった、単品で注文したいとかは、
　一旦、ひがまで連絡もらう必要があります。
　理由は、精算時に料金が合わなくなるためです。

**Comment by higachan0406** [comment]
>・みなし30人で予約。
>　→27人で予約。当日、3人増えた場合、入れるか確認。
>・カニは６。

27人、カニ6でお願いしました。

**Comment by PharaohKJ** [comment]
金額あった & 領収書だしたとうかがってます。クローズ。
