### ISSUE TITLE
広報

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#17]
- SNS担当
- 会場写真担当
- 会場レポート担当決め

**Comment by PharaohKJ** [comment]
もうウェブページ公開したので、戦略たててやること。

**Comment by yuuitiro** [comment]
Twitter アカウント取っちゃいますか。
jawsugkanazawa とかとってもかまわんですかね？

**Comment by PharaohKJ** [comment]
今後の運用を考えると悩んじゃうんだよなあ。ドアキのイベントをツイートし続けるマシーンになるとして、どれだけの人にみてもらえるかと言うと・・・。あーでも当日会場の実況もある程度やりたいし、作らざるをえないのかな。どうですかね？それもハッシュタグでカバーできるのかな。

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday どうですかね？ ↑
とりあえず、来週中に決めましょう。

**Comment by yuuitiro** [comment]
最初 専用アカウントとってそちらでツイートするイメージで考えていましたが、今更新規アカウント取ってフォロー集めて拡散することを考えると、communitydayとしてのメリット薄いっすね。

アカウント取得して communityday 以後の運用を前提に活用するならば作る意義あるかな。

自分はそもそも鍵垢なんで、波及させる力が弱い :(

**Comment by TAKAyukiatkwsk** [comment]
来客者の目線だと、community dayなりJAWS-UG金沢なりの公式アカウントがあるとそれを真として情報を得たり動けたりするので嬉しいのかなと思います。(会場運営的にもやりやすくなるかも？)
イベント後もアカウントを活かせる方法があるとより良いとは思いますが 💦

専用アカウント取る取らないに限らず、ハッシュタグは用意しておいた方がよいと思います。

**Comment by PharaohKJ** [comment]
フォローしてね、って宣伝するがめちゃくちゃ大変なんだよなー。迷う。

**Comment by yuuitiro** [comment]
アカウントは取っちゃって、今回に限ってハッシュタグに一票。

今回のイベント前にアカウントを活用するのは時間的猶予もないので、イベント後にアカウントを活用する道を考えたらどうでしょうか？

**Comment by yuuitiro** [comment]
ちょっと追記。

「フォローしてね」って宣伝するのは今回のイベント中で :)

**Comment by PharaohKJ** [comment]
確かUGの電子メールアドレスあったんで、それでtwitterアカウントとってしまいます。

**Comment by yuuitiro** [comment]
おねがいしまーす

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday 
https://twitter.com/jawsug_kanazawa
作成しました！とりあえず @yuuitiro さんにはIDとパスワード教えておきます。それ以外の方は連絡ください。

**Comment by PharaohKJ** [comment]
@yuuitiro さん、ツイートしてほしい内容を何かしらの方法で連絡するんで、ツイートしていってほしいです。で、それをFacebook連携でJAWS-UG Kanazawa公式ページに転送する。という運用にしようと思います。

連携までは @PharaohKJ がやります。

この方法でどうですかね？

**Comment by PharaohKJ** [comment]
@yuuitiro さん、連携したSNSに投稿するという buffer というサービスがありまして、それのアカウントを取得、UG金沢のtwitterとUG金沢のFacebookページへの連携を行いました。

そのページにログインし、投稿すると両方ともに反映されるので、試してみてください。
bufferのログインIDとパスワードはslackのDMでお送りします。

**Comment by yuuitiro** [comment]
@PharaohKJ おはよーございます。了解です！

**Comment by yuuitiro** [comment]
slack DM でも返しましたが、ログイン確認できました。

**Comment by PharaohKJ** [comment]
@yuuitiro さん、今週末日曜日から1ヶ月前 & ドアキ公開予定ということで、私と手分けして毎日ツイート( & FB自動ポスト)していこうと思うのですが、ご都合いかがでしょうか？企画としては

- 登壇者情報を流す
- 準備の進捗をツイートする

といった感じかなあと。お互いかぶらないようにスプレッドシートあたりに計画と原稿書いていきます？

**Comment by yuuitiro** [comment]
@PharaohKJ 了解です。どういうタイミングで始めたらとも思ってました。スプレッドシートもいいと思います。

僕の方は、23日に帰国なので（って書き方するとえらそーですね）、22日夜から23日一杯まではちょっと手が空きませんってところです。それ以外はOK。

**Comment by PharaohKJ** [comment]
https://docs.google.com/spreadsheets/d/1wUiMIYxDEn0YbEdUZm5mHlXIA8VSXVLett_5Tp-hNHQ/edit?usp=sharing

シート作りました。ここでやっていきましょう。

**Comment by yuuitiro** [comment]
了解ですー！

23日の13:00分ですけど、この時間はちょっと難しくて加藤さんにお願いする感じでもいいでしょうか？
ちょうど出国手続きしているところかな。。

**Comment by PharaohKJ** [comment]
Buffer は投稿時間を指定して予約投稿できますぞ！
-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pharaohkj / twitter: PhalanXware

**Comment by PharaohKJ** [comment]
#34 が決まり次第、含めてポストしていくこと。

**Comment by yuuitiro** [comment]
一日 delay してしまいました 😓 

```
AWS Community Day Kanazawa 11/20  キーノートセッションには、アマゾン ウェブ サービス ジャパン株式会社 エバンジェリスト 亀田 治伸さんが登壇します。 https://buff.ly/2J71h5O #jawsug  #awscommunityday
```

2019/10/21 13:00 で tweet を予約

**Comment by yuuitiro** [comment]
一回様子みて次を予約します。

**Comment by PharaohKJ** [comment]
@yuuitiro さん
タイムテーブルまだ（仮）ありますが、作成しました旨、明日ぐらい(2019-10-22)に宣伝してほしいです！

**Comment by yuuitiro** [comment]
@PharaohKJ 10/22 13:30 に予約しました。

```
AWS Community Day Kanazawa 11/20  タイムテーブル(仮)を公開しました！ https://awscommunityday2019.jaws-ug.jp/#timetable  #jawsug  #awscommunityday
```

タイムゾーンがBSTだったのにちょっと焦りましたが :)

**Comment by PharaohKJ** [comment]
@yuuitiro さん
27日からのネタ一応書いておきました。新幹線復帰ネタどっかで入れます。

**Comment by PharaohKJ** [comment]
@yuuitiro さん
今日(2019-11-02)〜2019-11-05まで紹介文で仕込んでおきました & タイムゾーン設定をTokyoにしておきました。

**Comment by matyuda** [comment]
@PharaohKJ さん
ご当地お菓子で皆さんのご来場をお待ちしております！
https://drive.google.com/open?id=1O9hLwCRtnH8oig6sacs3voDZ0eTr9_ob
で紹介文仕込んでください。

**Comment by yuuitiro** [comment]
@PharaohKJ Buffer 弾切れなんだけども、従来のスタッフ紹介で埋めておきます？
カニであおっておきます？

**Comment by PharaohKJ** [comment]
カニは割増じゃないと食べられないからなあ、、、でもまぁそれとは関係なく紹介していいか。


-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pharaohkj / twitter: PhalanXware

**Comment by matyuda** [comment]
あと2日になりましたので、カウントダウンの告知はいかがでしょうか？

**Comment by PharaohKJ** [comment]
そのネタ最高。夜に流しておきます！
-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pharaohkj / twitter: PhalanXware

**Comment by matyuda** [comment]
@PharaohKJ さん

明日の１８時に下記で案内をお願いします。

----
明日 AWS Community Day 金沢が開催されます。
皆様とクラウドについてまる1日お話できることを楽しみにしております。
明日参加できない方のためにライブ配信を企画することとなりました。
（一部非公開セッションあり）

視聴ご希望の方は、公式チャネルを登録してください。
https://www.youtube.com/channel/UCkcXqRZEm1TEaJP0chkZlKQ

**Comment by matyuda** [comment]
@PharaohKJ さん

２０日の６時に下記で案内をお願いします。

----
本日１０時３０分より AWS Community Day 金沢が開催されます。
皆様とクラウドについてまる1日お話できることを楽しみにしております。
本日参加できない方のためにライブ配信を企画することとなりました。
（一部非公開セッションあり）

視聴ご希望の方は、公式チャネルを登録してください。
https://www.youtube.com/channel/UCkcXqRZEm1TEaJP0chkZlKQ

**Comment by PharaohKJ** [comment]
@matyuda さん文字数がめっちゃオーバー！ハッシュタグなどあるので 80文字ぐらいでお願いします。
![スクリーンショット 2019-11-18 22 35 37](https://user-images.githubusercontent.com/1581985/69056645-c0b6f300-0a53-11ea-82a4-716ca4a5940a.png)

**Comment by matyuda** [comment]
@PharaohKJ さん

２０日の１０時に下記で案内をお願いします。

----
AWS Community Day 金沢の受付が始まりました。
皆様とクラウドについてまる1日お話できることを楽しみにしております。
本日参加できない方のためにライブ配信を企画することとなりました。
（一部非公開セッションあり）

視聴ご希望の方は、公式チャネルを登録して１０時３０分からの配信をお待ちください。
https://www.youtube.com/channel/UCkcXqRZEm1TEaJP0chkZlKQ

**Comment by matyuda** [comment]
@PharaohKJ さん
文面見直しました。これでも長いでしょうか？

**Comment by PharaohKJ** [comment]
ギリギリまだ長いというか、140文字全部使っちゃう。ハッシュタグなど入らないので、以下文面でいきましょう。

AWS Community Day Kanazawa は明日開催です。10:30のキーノートより、ライブ配信も企画しておりますので、ぜひ公式youtubeチャンネルをご登録ください。https://www.youtube.com/channel/UCkcXqRZEm1TEaJP0chkZlKQ  #jawsug  #awscommunityday

**Comment by matyuda** [comment]
@PharaohKJ さん
宜しくお願いします！

**Comment by PharaohKJ** [comment]
予約完了

**Comment by PharaohKJ** [comment]
UG金沢公式アカウントでリツイしかやる暇なかったw
まぁよかった。ありがとうございましたツイートを 10:00 に仕込んだ。クローズ。
