### ISSUE TITLE
当日スケジュールをどうするか

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#18]
会場は10時から22時まで押さえているので、そのなかで設定できます。

## 案1
10時 - 18時 昼食付き + 打ち上げで飲み屋

- メリット
普通の時間

- デメリット
名刺交換会的なものも含めて18時なので忙しいか

## 案2
13時 - 21時 夕食付き + 打ち上げで飲み屋

- メリット
会社帰りに立ち寄ることができる

- デメリット
夜登壇してくれる？
帰りが遅くなる、電車問題、北陸三県勢が日帰りできない？

## 案3
10時 - 18時 昼食付き + 立食懇親会 + 打ち上げで飲み屋

- メリット
案1よりは忙しくないか

- デメリット
クラウドロードショーのときみたいに誰もこないってことがないようにしたい・・・

## 案4
10時 - 21時 昼食・夕食付き + 打ち上げで飲み屋

- メリット
ガッツリ

- デメリット
帰りが遅くなる、電車問題、北陸三県勢が日帰りできない？
疲れそう・・・。そんなにセッション用意できる？

**Comment by PharaohKJ** [comment]
弁当発注数とかケータリングとかも含めると参加人数感とかも含めて、スポンサー(協賛企業、登壇者)にお伺いしてから、かな？

どうやって決めるか、から。

**Comment by yuuitiro** [comment]
松本は素直に案１か案３に一票を投じます。
やっぱり *日帰り* できないのは翌日の仕事に響いてしまいます。
会場を22時まで押さえてあるならば、11時 - 19時 みたいな線でも行けそうですね:)

**Comment by higachan0406** [comment]
11月20日は水曜ですか、飲む人も次の日みちゃいますね。。

**Comment by matyuda** [comment]
準備時間含めて考えると案2が良いかと思いますが、
案3をベースに12時～20時で、立食懇親会を19時からのプランも良いかと思います。
仕事帰りにセッションを聞くことも出来るでしょうし、日帰り勢の方は19時に帰ると間に合うこと
飲み会までは行きたくないが、少し懇親したいという人にもちょうど良いかな？とも思います。

**Comment by yuuitiro** [comment]
↑ お尻の時間は、19時で一旦キリをつけるってのはいいと思います。

**Comment by PharaohKJ** [comment]
from @matyuda 
準備時間含めて考えると案2が良いかと思いますが、
案3をベースに12時～20時で、立食懇親会を19時からのプランも良いかと思います。
仕事帰りにセッションを聞くことも出来るでしょうし、日帰り勢の方は19時に帰ると間に合うこと
飲み会までは行きたくないが、少し懇親したいという人にもちょうど良いかな？とも思います。

**Comment by PharaohKJ** [comment]
今日ITBP武蔵いくんで、準備にはやめにはいられるのか確認してきます。
そうじゃなかったら10時から勉強会開始は無理になっちゃうんで。

**Comment by PharaohKJ** [comment]
延長料金払ったら、9時から入られるそうです。このパターンでいきませんか？

9時準備
10時開場
17時本編終了、立食懇談会へ
19時00終了、片付け
20時 非公式打ち上げ飲み会

**Comment by higachan0406** [comment]
>17時本編終了、立食懇談会へ

これは昼食とは別の夕飯？(柿ピー用意、ビール用意など)になりますか？
予算見る必要がありますか？

**Comment by PharaohKJ** [comment]
すみません、わかりにくくなっちゃったんで整理しました。予算別に見る必要があります。

懇親会 > 立食懇親会のこと > #15 で議論
これまで懇親会としていたこと > 非公式打ち上げ飲み会（割り勘） > #14 で議論

とします。よろしくおねがいします。

**Comment by PharaohKJ** [comment]
スケジュールは 

https://github.com/jaws-ug-kanazawa/aws-community-day/issues/18#issuecomment-523738201

でいったん確定としましょう。

**Comment by PharaohKJ** [comment]
キーノートをやろう！ということなどなどで、時間再度調整した版を企画書のほうにまとめました。

@jaws-ug-kanazawa/communityday 各位

https://paper.dropbox.com/doc/JAWS-UG-Kanazawa--Ak2hI~6XCf3lkQDpW6HP1JLeAg-j5Ogic0Xj9O4zctTLL2p8#:uid=867873529052457712903385&h2=%E4%BC%81%E7%94%BB

レビューお願いします。まぁこれで問題ないかな？

**Comment by matyuda** [comment]
良いと思います。
17時20分からトラック2側にある予備枠についてですが、懇親会に参加されない方向けに名刺交換の時間としても良いかと思います。

また、細かい点ですが、
#7 よりトラックはトラック1,2からトラックA,Bに変更する案となっていますが、確定でしたら企画書並びにホームページも変更をお願いします🙏（ホームページ側は今後の変更のタイミングで構わないと思います）

**Comment by PharaohKJ** [comment]
お、そうですね。そのようにしておきます。

- [ ] ウェブページ、企画書などトラック番号を正しく書くこと

**Comment by PharaohKJ** [comment]
↑、ウェブページ、企画書修正済み。いったん完了
