### ISSUE TITLE
会場内案内ポスター・貼り紙

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#19]
- ビル入り口 
- ~~エレベーター内~~
- ハンズオン開場前
- 6階受付前
- 制作担当
- 印刷業者発注
- 受け取り

**Comment by PharaohKJ** [comment]
@matyuda さん、ちょっとこれ見積もりしてもらっていいですかね？パンフを張り出して、表紙を使い回すのでもいいかなあ。

**Comment by PharaohKJ** [comment]
- [x] 受付
- [x] ハンズオン会場
- [x] 会場A
- [x] 会場B
- [x] ゴミはこちら

ぐらいの貼り紙の準備

**Comment by matyuda** [comment]
片面のフォト光沢紙という材質であれば、A3 1,290円/枚　B3 1,600円/枚　です。
印刷ではなくレーザプリンタでの出力だそうです。

概算レベルでは、B3×10枚(ごみ箱案内のポスターは多め)で16,000円でお願いいたします。
パンフレットよりも高いですが。。。。汗

数枚程度でA4でOKなら、自宅のインクジェットプリンタでも行けそうな気がしますが、デザインの色成分の指定が厳しいので、多少高くても上記金額で見積もっておいた方がよさそうです。

**Comment by PharaohKJ** [comment]
単にでかい文字、白黒をコピー用紙でいい、なら、コンビニのネットプリント(PDFやワードをWebサービス経由で印刷できる)でよいでしょう。初期印刷30円、複写10円ぐらいかな？

掲示物企画して、具体的にまとめていってほしいです。リストができたらロジ部に搬入リスト作ります。

印刷に時間のかかるような大きな掲示物は置けないと思ってるんですが、上記企画すすめましょう。

- 必要そうな掲示物の名前 ( 燃えるゴミ
- 概要 ( 燃えるゴミはここに捨ててくださいマーク
- どこで使うか ( 懇親会時、受付近くのゴミ箱で
- 欲しいサイズ ( A4 白黒
- どうやって作るか ( プリンターで印刷

のリスト作ってもらっていいですか？google spread sheet がよいと思います。

-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pxw_kato / twitter: PhalanXware

**Comment by matyuda** [comment]
コンビニのネットプリントについては調査しておきますが、コンビニのプリンタだとA3、B4が最大サイズかもしれません。
掲示物のリストについては作成しますね。

**Comment by PharaohKJ** [comment]
A4でバカでかい文字で十分だと思いますよ。それか、A4に1文字ずつ印刷するとか。

**Comment by matyuda** [comment]
掲示物のリストを用意してみました
https://docs.google.com/spreadsheets/d/1rOzMBqQ-KTLnODSh8UCcfwSAIQSvN6f4tx84C65aXfQ/edit?usp=sharing

**Comment by PharaohKJ** [comment]
ありがとうございます。掲示物増える場合にはここで @matyuda さんにお願いしてそのシートで管理するということにしましょう。

スポンサージョブボード、チラシはまた別のタスクで管理しましょう。

**Comment by PharaohKJ** [comment]
[Home · jaws-ug-kanazawa/aws-community-day Wiki](https://github.com/jaws-ug-kanazawa/aws-community-day/wiki#%E5%BD%93%E6%97%A5%E6%8E%B2%E7%A4%BA%E7%89%A9%E7%AE%A1%E7%90%86)

に記載しました。よろしくおねがいします。

**Comment by matyuda** [comment]
ありがとうございます！

**Comment by PharaohKJ** [comment]
AWSさんが立ちロールを2枚手配してくれるので、それも含めた、ポスター貼るところの決定

**Comment by PharaohKJ** [comment]
会場の担当宮本さんと話したのですが、エレベーター内の張り紙は会場NGになってしまいました。

**Comment by PharaohKJ** [comment]
wiki の会場レイアウトより再度まとめました

それぞれ必要数 + 予備1部を印刷してほしいです

- ゴミ箱案内
  - もえるごみ
  - ペットボトル
  - 缶
- 6F 会場A & B へ、案内(5F階段前に貼る)
- 5F ハンズオン会場へ(6F階段前に貼る)
- A4縦2枚連結ポスター (1階入り口エレベーター前に展示)
- スタンドポスター (AWSさまで2つ用意いただける)
  - 6F受付に1つ設置
  - 5Fエレベーターでて通路突き当り設置
- A4 会場A 内容案内 (会場A入り口に掲示)
- A4 会場B 内容案内 (会場B入り口 & 5Fの旧喫煙書あたりに掲示) 
- A4 ハンズオン会場 内容案内(ハンズオン会場入口に展示、受付は6Fという内容も書いてほしい)

**Comment by matyuda** [comment]
@PharaohKJ さん

スタンドポスター はどのようなイメージでしょうか？
他のポスターもデザインを合わせた方が統一感が出るかと思っています。

A4 会場A 内容案内 (会場A入り口に掲示)　は下記のようなイメージで良いでしょうか？
セッション情報は更新しておきます。
https://github.com/jaws-ug-kanazawa/aws-community-day/blob/master/%E6%A1%88%E5%86%85%E3%83%9D%E3%82%B9%E3%82%BF%E3%83%BC/%E7%A2%BA%E8%AA%8D%E7%94%A8PDF/%E3%83%88%E3%83%A9%E3%83%83%E3%82%AFA.pdf

**Comment by PharaohKJ** [comment]
@matyuda さん
スタンドポスターについては以下を参照してください
https://drive.google.com/open?id=1TnvBJb6ud1KGyBMQgeIGBbGyFeVpYo3d

案内はそのようなイメージで最高です！
手間なら画像いらないかも、画像よりスポンサーロゴのほうが喜ばれるかも。
いろいろ考えちゃいますが、部屋の名前と演題がわかればOKです！

**Comment by PharaohKJ** [comment]
最初にお車の方、未成年の方は飲酒厳禁ポスター

**Comment by matyuda** [comment]
@PharaohKJ さん
ポスター類の準備が遅くなっていて申し訳ありません。トラックAについて作成しましたので、ご確認ください。
行間が不揃いな点がありますので、可能な限り調整します。

なお、サイズはB3になりますので、B4 2枚で印刷してテープでつけてB3にする予定です。

**Comment by matyuda** [comment]
@PharaohKJ さん
案内ポスター取り急ぎすべて作成したつもりですが、漏れがありましたらご指摘ください。
https://github.com/jaws-ug-kanazawa/aws-community-day/tree/master/%E6%A1%88%E5%86%85%E3%83%9D%E3%82%B9%E3%82%BF%E3%83%BC/%E7%A2%BA%E8%AA%8D%E7%94%A8PDF

@TAKAyukiatkwsk さん
ハンズオン会場のポスターはこちらで問題ないかご確認ください。
https://github.com/jaws-ug-kanazawa/aws-community-day/blob/master/%E6%A1%88%E5%86%85%E3%83%9D%E3%82%B9%E3%82%BF%E3%83%BC/%E7%A2%BA%E8%AA%8D%E7%94%A8PDF/%E3%83%8F%E3%83%B3%E3%82%BA%E3%82%AA%E3%83%B3.pdf

**Comment by PharaohKJ** [comment]
@matyuda さん
いいと思います。ゴミの種類の英語、これどこか参照あります？あってるかどうかレビューできないw
あと、全体的にPDFファイルのサイズがでかいのは、これ小さくなりませんかね？
いや、コンビニプリントのアップロード容量制限にひっかかるんで、手持ちのmacでファイルサイズ
小さくしてからアップロードしてるんですけど、何が違うのかわからなくてやってるんですよね。

**Comment by PharaohKJ** [comment]
@matyuda さん
俺が印刷してもってく？どうします？

**Comment by TAKAyukiatkwsk** [comment]
@matyuda すいません、確認遅れました。よいと思います！
1点だけ、「受付は6Fにありますので〜」というところなのですが、
これってコミュニティデイ自体の受付を指していますか？
ハンズオン部屋でも、ハンズオン自体の受付(ドアキの参加希望した人を優先して入れたいので)を実施しようと思っていますが、表記としてどうしましょうかね？
ハンズオンの受付について参考:
https://paper.dropbox.com/doc/AWS-Community-Day-aPcPdOpHKYLH5YVM9WRUk#:uid=797281247689747887830703&h2=%E5%BD%93%E6%97%A5%E4%BC%9A%E5%A0%B4%E6%BA%96%E5%82%99%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB

**Comment by matyuda** [comment]
@TAKAyukiatkwsk さん
ご確認頂きありがとうございます。
6階の受付の件はご指摘の通りです。
そうしましたら、ハンズオンにも受付があることを記載しておきますね。

**Comment by matyuda** [comment]
@PharaohKJ さん

PDFのサイズについては印刷を私が担当しますので、対応します。

英語の件は、多少心配ありますが、登壇者の方含めて多国籍での参加になりますので、バランス考えてこのままとさせて頂きたいと思います。

**Comment by TAKAyukiatkwsk** [comment]
ありがとうございます！

**Comment by matyuda** [comment]
@TAKAyukiatkwsk さん

内容追記しておきました。もしお時間ありましたらご確認ください。
万一、まずい点がありましたらお知らせください。
