### ISSUE TITLE
イベントページ公開

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#20]
こっちがイベントのメインページ。ここからドアキに誘導してチケットをとってもらう。

- [x] デザイナー手配
- [x] スポンサーチェック
- [x] 公開

**Comment by PharaohKJ** [comment]
AWSさまよりCommunity Dayクリエイティブをいただいているので、進める。

[15VISION](https://15vision.jp/) さんにお願いしようと思っています。現状打診したところ、運営協力スポンサーとしてお手伝いいただけそうとのこと。

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday なんかこんな感じの、ってページある？

https://aws.amazon.com/jp/events/community-day/

をみると、色のテイストとかはあるけど、JAWS-UG金沢っぽさを出したほうがいいのかな。

https://aws.amazon.com/jp/summits/tokyo-2019/

こんな感じで、白メインで文字色黒、シンプルな感じ、でいいですかね？

**Comment by higachan0406** [comment]
色味は下の白メインがよいと思いました。

**Comment by TAKAyukiatkwsk** [comment]
私もAWSサミット東京のようなシンプルな感じでよいと思います。

> JAWS-UG金沢っぽさ

どこかにJAWS-UG金沢のロゴを含めておくと良さそうではありますね。

**Comment by PharaohKJ** [comment]
ウェブページ要件

https://aws.amazon.com/jp/summits/tokyo-2019/
https://jawsdays2019.jaws-ug.jp

 を参考にしたい、以下※印は動的に更新あり。決まり次第追加・更新していきたい。

- [x] ロゴ
  - [x] CommunityDay
  - [x] JAWS-UG 金沢
  - [x] 上記が共催してるようなロゴ
  - [ ] ↑をスタッフTシャツにしたい
- [x] タイトル  AWS Community Day Kanazawa
  - ↑ちょっとタイトルは共催スポンサーと要相談
  - ↑ 2019-08-29 タイトルを JAWS-UG Kanazawa x AWS Community Day 2019 Kanazawa から変更、UG Kanazawaの名前をどう入れていくかは共催スポンサーAWSさんと調整中
  -  2019-09-06 確定済み
- [ ] 概要説明
- [ ] doorkeeper（チケット購入ページ）への案内
- [ ] セッション情報 ※
  - https://aws.amazon.com/jp/summits/tokyo-2019/ の基調講演みたいな味で
  - 登壇者名・登壇者顔写真（あれば）・タイトル
- [ ] スポンサー・スポンサーロゴ一覧
  - [ ] 登壇スポンサー一覧  ※
  - [ ] ほかスポンサー一覧 ※

**Comment by ichigami** [comment]
イベントページ制作を行う15VISION いちがみです。
みなさん、よろしくお願いいたします。
加藤さん、トップページの構成要素ありがとうございます。
明日、構成案を提示します。

1点お願いがあります。JAWS-UG 金沢のロゴデータも支給していただけますか。
よろしくお願いいたします。

**Comment by PharaohKJ** [comment]
@ichigami さん、JAWS-UG金沢ロゴは

https://github.com/jaws-ug/logo/tree/master/kanazawa

からもっていってください。 @aibax さん↑でいいですよね？

よろしくおねがいしますー。

**Comment by PharaohKJ** [comment]
@ichigami さん、すみません、イベントタイトルを変更しました。

**Comment by ichigami** [comment]
ざっくり構成案を作成しました。
ご確認をお願いします。
https://xd.adobe.com/view/70ab6318-f721-44bc-68f9-bf39bd6b48ca-069a/

@PharaohKJ さん
随時更新していくコンテンツがなければCMSは入れなくてよいかなと思いましたがどうでしょう？

**Comment by PharaohKJ** [comment]
@ichigami さんありがとうございます。
よいと思います。

あっちのコメントにも書きましたがいちおうここにも書きますね↓割とスポンサーや登壇者はじっくり決まっていく( = 実質随時更新していく必要がある )と思っています 。

Presented by はたぶん、JAWS-UG KANAZAWA と AWS のロゴを並べることになると思います。スポンサーと相談します。

チケットは無料になると思うんで「無料チケットを取得」という表記にします。

CMSでもHTML+CSSでも楽なほうでお願いします。後者のほうがコード管理とかこっちでも手が出しやすくて助かります。

**Comment by higachan0406** [comment]
@ichigami
構成案見ました。いいですね！

**Comment by PharaohKJ** [comment]
@ichigami さん、WDF FInal のウェブペイジみましたが、あのまま使えるのでは・・・w

**Comment by ichigami** [comment]
@PharaohKJ さん、そうなんです。
WDF FInalのページは、a-blog cmsのLP用テーマを使ってつくっています。
今回もまずはa-blog cmsのLP用テーマでページ用意して、ひとまず確定した情報から入れ込んでいって最終的にデザインを整える、という流れにした方がスムーズかもしれません。

告知ページ公開予定日は、下記のPaperを見ると「9月20日（金）」となっていますが、それぐらいのスケジュール感と考えていてよいですか？
https://paper.dropbox.com/doc/Tasks-of-JAWS-UG-Community-Day--AkBne8CN9fgELja3x~9b9NTZAQ-9wjzxnOWz8lasdIWYQfhE

**Comment by PharaohKJ** [comment]
その日付は参加者用チケットページ( doorkeeper ) のお尻のつもりなんで、イベントページはなるべくはやく欲しいところです。

遅れてますがスポンサーに声かけるために、まずはみせられるこのとしてWebページと企画書と考えているのです。

よろしくお願いします。
-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pxw_kato / twitter: PhalanXware

**Comment by PharaohKJ** [comment]
@ichigami さん、基本的なテーマまでやっていただいて、他担当者でもCMSいじってコンテンツ変更できるようにする、ってやるのが一番楽でよいですかね？

**Comment by ichigami** [comment]
@PharaohKJ そうですね、そうしましょう。現状そんなに更新しやすいテーマではないのですが、なるべく更新しやすくなるように調整しながら初期のコンテンツ投入を行います。
a-blog cmsの動く環境を用意していただけますか。

a-blog cmsダウンロード
https://developer.a-blogcms.jp/download/
動作条件
https://developer.a-blogcms.jp/document/requirements.html

**Comment by PharaohKJ** [comment]
んんー、SaaS版ってないんですねえ。これはメンテ含めてだるいですね。
まぁいったん、作ってcurlして保存してあとはstaticサイトとして使うか・・・。
まぁセットアップします。

**Comment by ichigami** [comment]
@PharaohKJ やっぱり、いろいろコストっぽいのでstaticにつくりましょうか。

**Comment by PharaohKJ** [comment]
@ichigami もう少々おまちを本日中に用意します。

a-blog cms で作る > それの static を作成( curl あたりで自動作成) > staticで公開

するようにしましょう。なので更新するときだけ a-blog cms を起動するってことでいいかと思います。
少々お時間ください。なんかいろいろあって本日いっぱいいったんください。

**Comment by PharaohKJ** [comment]
@ichigami さん
http://awscommunityday2019.yaranaika.me

にとりあえず準備しました。IDとパスワードは公開できないんで、こっそり送付しました。
IDとパスワードは @PharaohKJ まで連絡ください。更新担当者にのみ配ります。

本番のドメイン名は @aibax さんが手配してくれています。少々お待ちを。
あとで入れ替えるつもりです。

**Comment by PharaohKJ** [comment]
↑ LightSail で構築、一応月1,000円のLightSailインスタンスで、費用は今度相談
@ichigami さん、CMSログイン確認待ち
直接ファイル編集したいということで @ichigami さんの公開鍵を登録済み

https://library.panic.com/ja/general/ssh-keys/?fbclid=IwAR2FDIajgzkigmQWSn92oAN5nrYbWENeTGZw52bZhYq3hzzTKDbK0CAv9rE#ssh-configファイル

を参考に `~/.ssh/config` に

```
Host awscommunityday2019.yaranaika.me
  User bitnami
```

とかけばつながりますので、ご確認よろしくおねがいします。

**Comment by PharaohKJ** [comment]
@ichigami さん
イベント名は 「AWS Community Day Kanazawa」
ウェブペイジ上段の「presented by」は、JAWS-UG金沢の右横（JAWS-UGロゴのほうが上手:カミテ）にawsのロゴもいれてください。先方OKもらってます。

@aibax さん、公式slack の #community-day-2019 でOKもらったんで

community-day-2019 .jaws-ug.jp

でドメイン申請お願いします。

**Comment by PharaohKJ** [comment]
@aibax さん、2019-09-04のslackでした議論で、これまでとあわせて

communityday2019 .jaws-ug.jp

でドメイン取得お願いします。

@ichigami さんと話して、CSS・テーマ作成有線で、コンテンツの入れ込みは分業して手伝う、いったん目標は来週いっぱい 2019-09-13 としました。

**Comment by PharaohKJ** [comment]
一発ウェブページの割に ablog のライセンスが高い ( 5万円 ) ので、要相談。↑のLightSailインスタンスの料金もあわせて。

いったん完成してCMSからstatic運用したとき、CSSとかJSのライセンスとか絡んでいろいろあるかも。そこも要調査。

**Comment by PharaohKJ** [comment]
ライセンス問題については解決。

**Comment by matyuda** [comment]
トップページのどこかに
https://communityday.awsugkol.org/
にあるようなカウントダウン入れていただくと盛り上がりそうですが、いかがでしょうか？

**Comment by PharaohKJ** [comment]
大きな機能追加はいったんパスしましょう。次はドアキ公開するときにあわせて追加したりなんだりしましょう。つまるところ、10月ですかね。

**Comment by ichigami** [comment]
@PharaohKJ さん
カンプにあわせてデザインを整えました。ご確認をお願いします。
http://awscommunityday2019.yaranaika.me/

データ当て込みについて不明点あればお問い合わせください。

**Comment by PharaohKJ** [comment]
@ichigami さん

ありがとうございます。いったんこれでいきましょう。火曜までにいったん私がコンテンツあてていきます。

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday 各位

- 会の説明文追加
- タイムテーブル修正
- 連絡先追加
- スポンサーロゴいったん非表示
- 登壇者いったん非表示

にしました。レビューお願いします。これを

- [ ] AWSさんにも出しOKをもらう
- [x] @aibax さんがドメインとっていただけて
- [ ] そのドメインでライセンスキーを発行
- [ ] https の設定する

したら公開しようと思います。

@aibax さん、IPは `54.92.19.125` でお願いします。

**Comment by TAKAyukiatkwsk** [comment]
LGTM!
些細なところで気になったのはJAWS-UG金沢のロゴで「AW」の部分が少し崩れているように見えるのはもともとそういうものなんでしょうか？

**Comment by PharaohKJ** [comment]
ほんとだね。なんでだろ。

**Comment by PharaohKJ** [comment]
@ichigami さん、JAWS-UGのロゴがなんか白黒反転する際になんかなっちゃったのか、文字がくずれてしまっているの、なおります？元データの不備なのかな。

![スクリーンショット 2019-09-16 12 20 09](https://user-images.githubusercontent.com/1581985/64932807-7b701c80-d87c-11e9-9600-44c30156f271.png)

**Comment by PharaohKJ** [comment]
難しいようでしたら、ロゴマークのみで、右側の文字は省いてしまってもいいかも。

**Comment by ichigami** [comment]
@TAKAyukiatkwsk さん、 @PharaohKJ さん
JAWS-UGのロゴ修正しました。ご指摘ありがとうございました。
http://awscommunityday2019.yaranaika.me/

どうもイラストレーターのデータに色のない透明なパスがあって、ロゴの色を黒→白にするときに、そのパスにも色をつけてしまっていました。

**Comment by PharaohKJ** [comment]
完璧。やったぜ。

**Comment by PharaohKJ** [comment]
AWSさんよりOKいただきました。最高です！という評価です。 @ichigami さんありがとうございます。

私の追加した文章のところで「AWS」→「アマゾン ウェブ サービス (AWS)」という表記変更だけ先方よりツッコミいただいてなおしました。

@aibax さん、 `awscommunityday2019.jaws-ug.jp` でライセンス発行申請中です。ドメイン取得よろしくおねがいします。

**Comment by PharaohKJ** [comment]
@aibax さん、ライセンスファイルが提供されました。ドメイン設定して、httpsの設定とかに進みたいのでよろしくおねがします。

**Comment by aibax** [comment]
jaws-ug.jp ドメインにサイトのホスト名登録完了しました。
<img width="596" alt="dig" src="https://user-images.githubusercontent.com/4516376/65372161-45310380-dca7-11e9-8cab-5607e062056a.png">

**Comment by aibax** [comment]
サイト見れるようになりました。
http://awscommunityday2019.jaws-ug.jp/

**Comment by matyuda** [comment]
@aibax さん
ご対応いただきありがとうございました。

こちらのページにリンクを掲載していただくためには、沼口さんへお願いすることになりますか？
https://aws.amazon.com/jp/events/community-day/

**Comment by PharaohKJ** [comment]
きいてみます。

**Comment by PharaohKJ** [comment]
申請中とのことです。

**Comment by PharaohKJ** [comment]
とりあえず公開したのでここはクローズしますね。
