### ISSUE TITLE
スポンサーロゴ掲載

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#22]
https://docs.google.com/spreadsheets/d/1h23OuAH86_VcUPLnEOCj__bJUDPPSf-2QB9mLpSSucw/edit?usp=sharing

↑フォームに投稿があったらここが追加されていくので、これの何行目まで対応したか、ここで進捗記録していきます。

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday の方々はみんな運営協力なはずなので、よろしければぜひ↑。
といってもほぼ個人でやってる連中だけになっちゃうか。

**Comment by PharaohKJ** [comment]
800x800以上の正方形サイズに変換して掲載すること

```
convert logo-original.png -gravity center -background transparent -extent 1000x1000 padding_logo.png
```

[加工前後の画像付き！ImageMagickのオプションを最高に分かりやすく解説してみた - bitA Tech Blog](https://tech.bita.jp/article/27)

**Comment by PharaohKJ** [comment]
2rythm さんまで掲載済み

**Comment by matyuda** [comment]
@PharaohKJ 案内パンフレットにロゴを掲載するため、掲載用ファイルのURLに参照権限をリクエストしておきました。お手数ですがご確認ください。

**Comment by PharaohKJ** [comment]
済ですー
-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pxw_kato / twitter: PhalanXware

**Comment by PharaohKJ** [comment]
DMM.com さままでロゴ記載済み

**Comment by PharaohKJ** [comment]
本日登録分まで掲載済み。掲載済みのものは黄色の背景色つけておきます。

**Comment by PharaohKJ** [comment]
インテックさままで掲載

**Comment by PharaohKJ** [comment]
@aibax さん 植木さんに登壇スポンサーとして御社ロゴも掲載できるのでよろしければ送ってくださいの旨お伝えください。URLは http://bit.ly/comday2019sponsorlogoform
岡本さんらにもお願いします。 @aibax さん自身のもお願いします。
esm勢にはさきほどメールしておきました。

**Comment by PharaohKJ** [comment]
esmさまのロゴ掲載

**Comment by PharaohKJ** [comment]
本日登録分掲載

**Comment by PharaohKJ** [comment]
@matyuda さん、AIファイルの編集ってできます？お手伝いいただきたいことがあるのですがお願いできますでしょうか。

**Comment by PharaohKJ** [comment]
編集済み。とりあえずこれ以上は増えない予定なので、クローズします。みなさんありがとうございました！
