### ISSUE TITLE
勉強会トラック配信部

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#23]

**Comment by PharaohKJ** [comment]
#7 より派生

**Comment by matyuda** [comment]
Slackより転記

Media JAWSの三浦さんにアドバイス頂きまして、
https://obsproject.com/ja?fbclid=IwAR1M12L8C0xwldvjpmGmXBgRiiKs-lndmEUh1As9DD9TYV3Qe-L4AD8rtes
こちらを利用して、リアルタイム配信してはどうか？という話がありました。

収録して後日配信は、つらいのでやめた方がいいとのアドバイスもいただいています。リソースが限られているのでバランスは大事ですが。。。

リアルタイム配信例
https://www.youtube.com/watch?v=YzDASQcTHwE&feature=youtu.be&fbclid=IwAR0_24_pAW9Cc16ttqRjupthfU9uEPm-ZfjaOaF6ktAfFc5s8FqMrND0YzE

**Comment by PharaohKJ** [comment]
当日配信のほうがリソースつらい説もあり。

ちょっと要件まとめませんか？

**Comment by PharaohKJ** [comment]
@matyuda さん、↑の件まとめお願いできますか？その資料もって、配信やってる子のところ相談にいきたいと思います。

**Comment by matyuda** [comment]
@PharaohKJ 承知しました。遅くなりましたが、要件整理始めます。
明日の録画についてですが、ライブ配信用のYoutubeのアカウント設定をしたところ、有効になるまでに２４時間かかるようです。明日、ライブ配信は間に合わない可能性があります。。。。間に合わない場合には、録画で進めたいと思います。

**Comment by matyuda** [comment]
10/5 プレイベントで検証すること

- [ ] 帯域幅チェック https://www.google.com/search?q=speedtest

- [ ] 音声入力の確認 プレゼン用のPCのマイクと会場マイクによってハウリングが発生しないかどうか

**Comment by matyuda** [comment]
収録要件を下記に整理します。

@PharaohKJ さん
委託先への打診にあたり、問題となる点がありましたらご指摘ください。

目的
- 来場することが出来ない方にも楽しんでいただくため
- JAWSUG金沢の取組を配信形式で知っていただくことによって、来ていただく敷居を下げる（逆に上がってしまう？） 
- 継続的に収録できるノウハウが習得できれば、ベター。

留意点
- 登壇者の方への許諾
- 来場者の方への許諾（NGの方が映り込むことを考慮すると、来場者の方が映らない方法をとることが望ましい）

収録形式
- トラックA、トラックBの2つを収録対象とする（できない場合には、初心者向けのトラックAのみ）
- 視聴者が内容を理解しやすいようにする為、スライドと登壇者の声を合わせた状態とする（できない場合には、登壇者とスライドが映った状態をビデオカメラで録画する）
- Youtube等への録画、後日配信を前提とする（会場内の帯域不足が懸念される）
- スタッフ不足が発生することが予想されるため、予算が許されれば、委託を検討

自力でやる場合には、下記方法を想定
トラックA・・・OBS Studioが入ったノートパソコンにUSB等で接続可能なピンマイクを用意して、登壇者の方に使っていただく（登壇の開始、終了時点のみのスタッフのフォローで乗り切りたい）
トラックB・・・三脚にビデオカメラをつけて、録画しっぱなしにしておいて、セッション終了ごとに録画を一時停止する

**Comment by PharaohKJ** [comment]
人手不足はなんとかできそうですか？結構キツそうです。どれだけの人員が要りそうか教えてください。
カメラ役ベタ付き必須なので会場にずっといないといけないですよねえ？2会場、午前・午後交代制として4人ですかね？

ちょっと人員希望表作らないといけないですね。これは準備始めます。

撮影OK、公開OK、他に何かお願いしないといけないこと、接続端子などなど、登壇者に電子メールでおうかがいしようと思いますのでその文章と質問項目の作文をお願いします。

上記文章で外部の会社に相談してみればよいですか？提案含めてうkがいますか。
-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pharaohkj / twitter: PhalanXware

**Comment by PharaohKJ** [comment]
人員希望表は作りました。wikiを参照してください。
https://github.com/jaws-ug-kanazawa/aws-community-day/wiki#人員希望

外部の会社に今日・明日中に連絡とってみます。

**Comment by PharaohKJ** [comment]
@matyuda さん
外部の会社さんと打ち合わせの段取りしています。

- 10/17 明日
- 10/18 明後日
- 10/20 日曜15時以降で先方事務所

のどこかで打ち合わせできるとのことです。10/20は私ちょっと対応できなくて & @matyuda さんとしては平日は夜以外キツイと思いますのでおまかせします。

平日夜、テレカンで、が一番現実的なあたりかな・・・先方が対応してくれればのはなしですけど。

↑のスケジュールのどこで & どんな方式にしましょうか？お返事ください。先方とつなげます。

**Comment by matyuda** [comment]
@PharaohKJ さん

お返事遅くなりすみません。
登壇者への電子メールのおうかがい文章と質問項目の作文しておきます。
カメラ役と「司会進行 & アナウンス & 登壇者サポート」を兼ねられれば良いのですが、難しそうでしょうか？（設置場所による？）

外部の会社さんとの打ち合わせについてですが、
10/17, 18は申し訳ありませんが、私の都合がつきません。

10/20でしたら、18時ごろお伺いできると思います。
10/21の週の平日の場合、19時であれば大丈夫です。
10/22の祝日がご対応いただけるようであれば、何時でも大丈夫です。

**Comment by PharaohKJ** [comment]
> カメラ役と「司会進行 & アナウンス & 登壇者サポート」を兼ねられれば良いのですが、難しそうでしょうか？（設置場所による？）

私の経験上とてもむずかしいと思います。おっしゃるとおり、設置場所にもよると思いますが、録画サポートも含めて、人数を2とするならギリギリいけるかな、、、と思います。

10/20以降は1週間出張して国外出張で時差もありまして、テレカンでも対応できないので @matyuda さんと先方で話進めてください。スケジュール送っておきます。

**Comment by PharaohKJ** [comment]
Facebookメッセンジャで3人会議設定しました。そこで調整お願いしまーす。

**Comment by PharaohKJ** [comment]
日曜日、会社と @matyuda さんが直接お会いして企画説明 & 見積もりいただくことにした。

**Comment by PharaohKJ** [comment]
@matyuda さん、↑どうでした？

**Comment by matyuda** [comment]
@PharaohKJ さん

ご連絡遅くなりました。
打ち合わせ結果は下記の通りです。

xSplitを見せて頂いた感じでは、OBS Studioと同等のソフトウエア？と考えられますので、後述の案２を採用する場合においては、代用は可能と思います。

まずは、５万円の費用捻出が可能かどうか、２トラックの収録をするかどうか（１トラックのみに限定するかどうか）を判断する必要があります。

なお、取りうる選択肢が限られていたため、松竹梅のプランは用意できませんでした。

**収録方式について**

下記２案が検討できるが、登壇者が自分のPCを利用できない場合に不便を強いる可能性があることから原則案１となった。また、Youtube等へのリアルタイム配信を前提とする。
（録画した場合、ディスクIOの遅さが足を引っ張る可能性とディスク容量不足になる可能性を懸念）

案１）登壇者のHDMI出力を分岐して、プロジェクターへ出力するものと、キャプチャーカードを介してxSplitがインストールされたマシンに入力し、別途USBタイプのWebカメラの映像と共に合成する。
案２）xSplitが入ったマシンを登壇者の方に使っていただき、登壇者がPCで操作する画像をすべてキャプチャし、別途USBタイプのWebカメラの映像と共に合成する。

音声はUSBタイプのマイクを別途調達して、会場用のマイクとセットで登壇者の方に使っていただく。（ワイヤレスピンマイクがベター？）


**収録対象について**

会社保有の機材は、１セットとなっており、またお1人でのご対応となるため、トラックAのみでの収録を前提とする。

トラックBについては、録画（後日編集）を前提として、案２＋バックアップ用としてビデオカメラを置いたままにする方法は検討できる。（ただし、登壇者の方には配信できない可能性があることを伝えておく必要がある）


**費用について**

人件費と機材レンタル費用として５万円を希望。
５万円の費用捻出が厳しい場合には、応相談。

**Comment by PharaohKJ** [comment]
@matyuda さんありがとうございます。

ちょっといま外出てるので取り急ぎで恐縮なんですが、会場AはアナログRGB接続のみとなっています(いっしょに見学しましたっけ？資料参照のこと:wiki
ni aru )。大丈夫ですかね？
-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pharaohkj / twitter: PhalanXware

**Comment by matyuda** [comment]
アナログRGB接続は先方へも伝えました。
HDMI→RGBへの変換は２案どちらの方式でも必要　＆　先方も所有無し
とのことなので、調達が必要です。

下記３点について教えてください。
１．トラックB（ホール２）のプロジェクターは
#27 でお借りできるとのことですが、こちらはHDMI端子ついていますでしょうか？

２．トラックBのマイク＆スピーカーは
https://www.bp-musashi.jp/rental/machine.html
の音声入出力機器　を借りることになりますか？

３．よく分かっていませんが、
https://www.bp-musashi.jp/rental/images/6f_01.pdf
に記載のある
有線マイク（受付貸出）
マイクスピーカー
はホール１の映像・音響調整卓につながっているのでしょうか？？

**Comment by PharaohKJ** [comment]
HDMI > RGB は結構相性でるらしくて、注意してください、とのことです。

https://www.amazon.co.jp/サンワサプライ-HDMI-VGA変換アダプタ-HDMI-Aメス-VGAメス-AD-HD13VGA/dp/B00ID1S2U8/ref=sr_1_6?__mk_ja_JP=カタカナ&keywords=HDMI+メス+RGB+メス&qid=1571875982&sr=8-6

これでいいのかな？

> １．トラックB（ホール２）のプロジェクターは
> #27 でお借りできるとのことですが、こちらはHDMI端子ついていますでしょうか？

はい。paperのほうにも書いておきます。

> ２．トラックBのマイク＆スピーカーは
> https://www.bp-musashi.jp/rental/machine.html
> の音声入出力機器　を借りることになりますか？

↑のページにマイクとスピーカーの情報について書いてありませんね、、、。
ケーブルありのカラオケセットのようなマイクとスピーカーを借りる予定です。
（これは部屋の料金で借りられたはず）

> ３．よく分かっていませんが、
> https://www.bp-musashi.jp/rental/images/6f_01.pdf
> に記載のある
> 有線マイク（受付貸出）
> マイクスピーカー
> はホール１の映像・音響調整卓につながっているのでしょうか？？

いいえ、つながっていません。↑のとおり、トラックBはカラオケセットのようなやつです。
トラックAの映像音声調整卓からは、配線次第でトラックA & B のスピーカーに音声を流せるそうです。

**Comment by PharaohKJ** [comment]
案1に関してですが、これまで同じことをトライした経験からいうと、HDMI出力にコピープロテクション信号がある場合、表示されないということがありました。

ゲームならプレイステーションとかで機種が限られますが、パソコンとなるといろいろ難しいようです。

だいたい方向性はわかりましたので、実際のITBP武蔵でぶっつけ本番というわけにはいかないでしょうので、テストする段取りなど決めていってください。

トラックB用の収録機材は最悪スマホでなんとかなると思います。ビデオカメラどこかから調達できますかね？金払えば借りられるようですが、、、借りちゃう？(この機種で問題ないのかはすみませんちょっとわかりません)

**Comment by PharaohKJ** [comment]
某社の幹部とお話してHDMIアナログ変換やキャプチャデバイスをお借りすることができることになりました。

**Comment by PharaohKJ** [comment]
10/31 テレカン予定

**Comment by PharaohKJ** [comment]
@matyuda さん
登壇者に案内する収録していいですか？公開していいですか？の質問の文面をGoogle Formで作成してください。登壇者に電子メールで案内します。

スライドの公開可能・不可能、不可能な部分がある、などについて、登壇時最初にご案内いただけますようお願いいたします。

- スライドファイル後日公開しますか？
  - はい / いいえ
- 登壇内容参加者によるSNS拡散
  - 可 / 指示するところで一部否 / 否
- スライドの写真参加者によるSNS拡散
  - 可 / 指示するところで一部否 / 否

- 運営によるライブ配信
  - 可 / 否 / リアルタイム配信のみ可(録画を配信ことは否)
- 運営による録画とその録画をYoutubeなどで一般公開
  - 可 / 否

これぐらいかな？

**Comment by matyuda** [comment]
@PharaohKJ さん
承知しました。
Google Formでのアンケートフォーム作成が出来次第報告します。

**Comment by matyuda** [comment]
下記調整して報告要。
- [ ] URLの案内方法
- [ ] 視聴予定人数の整理

但し、当日来る予定の方が、オンラインに流れないように工夫する仕組みあり。

**Comment by matyuda** [comment]
スライドテンプレートについてもアンケートともに案内要。
スライド内に写真撮影OK/NGを入れて頂くなどの案内も必要。
https://github.com/jaws-ug-kanazawa/aws-community-day/blob/master/%E7%B4%A0%E6%9D%90%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88/%E7%99%BB%E5%A3%87%E8%80%85%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89.pptx

**Comment by matyuda** [comment]
３名で打ち合わせ

機器配線図を共有
https://drive.google.com/file/d/1JAg6vZSw01NgAgEAjxB8U21AI5TzadWn/view?usp=sharing

トラックA, トラックBをYoutubeでライブ配信する。
帯域不足があればBトラックは録画に切り替える。
配信用アカウントについては別途 @PharaohKJ  さんにてご確認いただく。

トランザムさんにて予算８万円内で手配（最大スタッフ３人）。

機材のレンタルについては、明日以降 @PharaohKJ さんよりお願いして頂く。
↓
レンタル日が決まり次第、トランザムさんへ持ち込んでテスト

後日、ITプラザ武蔵での接続テスト（HDMI→RGB接続、ライブ配信の帯域確認）を行う

@matyuda  にて配信用の企画書を用意する。

別途、登壇者席と配信用スペースを用意する　→ #13 にて考慮する。

**Comment by matyuda** [comment]
@PharaohKJ さん

アンケートフォーム作成しました。レビューください。
なお、ライブ配信の質問についての
リアルタイム配信のみ可(録画を配信ことは否)
の回答項目は、削除させていただきました。
（運営による録画とその録画をYoutubeなどで一般公開　の質問と重複しているため）

https://forms.gle/uUZuEMywyf9wAy498

**Comment by PharaohKJ** [comment]
> はい（撮影する必要がありませんとお伝えいただくことで、参加者に集中して聴いていただけます）

カッコ書き、いらないと思います。ていうかこんなメリットがあるなんて想像もしませんでした！マジ？

```
参加者による登壇内容についてのSNS拡散はしても構いませんか？ *
- OK
- （不特定多数への情報発信が）一部NGの内容の説明が含まれる
- NG
```

は

- OK
- 部分的にNG（不特定多数への情報発信がの内容の説明が含まれる）
- NG

としたほうがわかりやすそう

申し訳ありませんが一部(いちぶ) という表現より「部分的」という表現に改めたほうがいいかもですね。

```
運営スタッフによる録画ならびに録画内容をYoutubeなどで一般公開しても構いませんか？
```

は

運営スタッフによるYoutubeでの録画配信はしても構いませんか？

でいかがでしょうか。「ならびに」があると、前と後で質問が2つあってそれに対してOK/NGとなると返事が難しいかなあと考えました。あとYoutube以外は考えていませんよね？なんかのコンテンツに使うことあるか・・・まぁなど付けておくの安定ですかねえ。

**Comment by matyuda** [comment]
@PharaohKJ さん
ご指摘いただきありがとうございます。
本日中に修正しておきます。

なお、
撮影する必要がありませんとお伝えいただくことで、参加者に集中して聴いていただけます
については、「撮影する必要がありません」とすると撮影する人が減って、シャッター音がしなくなるというロジックです。他のイベントでもシャッター音問題がよく言われていますので、効果はあると思います。

**Comment by matyuda** [comment]
@PharaohKJ さん
修正完了しました。内容問題なければ、登壇予定の方へメールにてご案内お願いいたします。

**Comment by PharaohKJ** [comment]
Tシャツのサイズ確認とともにメールしました。

**Comment by matyuda** [comment]
@PharaohKJ さん

遅くなりましたが、企画書作成してみました。
ご意見をお願いいたします。
https://paper.dropbox.com/doc/AWS-Community-Day--An_4jaST6b3fy_fI0juYD_Y7AQ-0Zb9xS9UDTQeCv8bfNTHq

**Comment by PharaohKJ** [comment]
@matyuda さん
レビューしました。編集権限くれれば私のほうでも書いたのですが、なかったのでツッコミにしておきました！

今晩、AWSさんに説明しましょう。

**Comment by PharaohKJ** [comment]
https://www.youtube.com/channel/UCkcXqRZEm1TEaJP0chkZlKQ

チャンネル作った。共同配信とかできんのか、、、。

**Comment by PharaohKJ** [comment]
![スクリーンショット 2019-11-05 07 20 24](https://user-images.githubusercontent.com/1581985/68163014-ccf37880-ff9c-11e9-9e15-c467e2682103.png)
![スクリーンショット 2019-11-05 07 20 34](https://user-images.githubusercontent.com/1581985/68163015-ccf37880-ff9c-11e9-96e1-f87838814e21.png)

Youtubeのチャンネルの権限の追加でトランザムさん追加して管理してもらおうと思います。
配信終了したら権限を消すことでコントロールできるかと。

**Comment by matyuda** [comment]
@PharaohKJ さん
コメントいただいた内容を企画書へ反映しておきました。

**Comment by PharaohKJ** [comment]
@matyuda さん
私のコメント完了しておきました。

**Comment by PharaohKJ** [comment]
アイ・オー・データ機器さまからお返事いただけました。

トランザムさんと相談して企画説明書を追加し、送付します。
来週には機材レンタルできる予定です。

**Comment by PharaohKJ** [comment]
https://paper.dropbox.com/doc/T1Pp5qvTujGCUbjE51W8y


@matyuda san kyou no report

**Comment by matyuda** [comment]
@PharaohKJ さん

レポート確認しました。ありがとうございます。
本日宿題としました登壇者の映像を上部にスライドを下部に貼りこみするための背景画像を作成しました。
なお、ライブ配信を都度セッションごとに区切るとのことにつき、セッション完了後にYoutubeで配信するタイトル名については、コピー＆ペースとして頂けるだけとするためにテキスト（セッション番号＋セッション名　のリスト）を事前に用意しておき、配信担当の２名の方にお送りするようにいたします。

**Comment by PharaohKJ** [comment]
@matyuda さん
当日はポスターなどの設置は別の人にやってもらうので、配信部担当と朝イチで詰めて進めてください。
1時間だとセッティングギリギリとのことなので、まずはトラックAを10:30までにおえて、次トラックBを11:30までに進める、、、といった予定になっています。人員配置など、トランザムさんと朝イチ（もしくは、Facebook）でつめておいてください。

**Comment by matyuda** [comment]
@PharaohKJ さん
承知しました。

**Comment by matyuda** [comment]
https://docs.google.com/spreadsheets/d/18_BLpCHs5yW-cQNNuZpBL_72_nosxGZLet3LRapzbR0/edit?usp=sharing
より

配信NGの時間帯
トラックA
13:30～14:20 の後半
14:30～15:20 の後半
15:30～16:20

トラックB
NGのセッションなし
