### ISSUE TITLE
登壇者掲載

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#24]
進捗レポートを書くところ。手分けしてやることも検討。

@TAKAyukiatkwsk さんまで掲載済み

**Comment by PharaohKJ** [comment]
13列まで記入済み(金沢工業大学さま、クラスメソッドさま)

**Comment by PharaohKJ** [comment]
アイパブリッシングさままで記載

**Comment by PharaohKJ** [comment]
本日登録分まで掲載済み。掲載済みのものは黄色の背景色つけておきます。

**Comment by PharaohKJ** [comment]
あさいくるさんまで対応

**Comment by aibax** [comment]
@PharaohKJ 
トラックB 11:30-12:20 の館岡さんのセッション、予定していたタイトルで確定しました。
Webサイトのタイムテーブルから（仮）の表記を削除してください。

**Comment by aibax** [comment]
@PharaohKJ 
トラックB 14:30-15:20 の枠で館岡さんにセキュリティについて話していただけることになりました。
セッションタイトルは「これだけは抑えておきたい！AWSにおけるセキュリティ」

**Comment by PharaohKJ** [comment]
done
全部うまった！

みなさんありがとうございました！
