### ISSUE TITLE
飲料の発注と運び込み

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#26]
#15 より

https://github.com/jaws-ug-kanazawa/aws-community-day/issues/15#issuecomment-534070503

３．お茶
　　[烏龍茶](https://www.amazon.co.jp/Amazonブランド-Happy-Belly-烏龍茶-500ml×24本/dp/B0784N26FV/ref=sr_1_12?__mk_ja_JP=カタカナ&keywords=烏龍茶+ペット&qid=1569425341&sr=8-12) 24本 x 2箱 3,192‬円
　　[緑茶](https://www.amazon.co.jp/Amazonブランド-Happy-Belly-緑茶-500ml×24本/dp/B077RVKFNK/ref=pd_sbs_325_1/355-0599288-8791958?_encoding=UTF8&pd_rd_i=B077RVKFNK&pd_rd_r=994709c8-b3fa-4c75-a762-f1f1364031e5&pd_rd_w=COBcO&pd_rd_wg=JXOc0&pf_rd_p=ad2ea29d-ea11-483c-9db2-6b5875bb9b73&pf_rd_r=NRT85V0WZ9KWYXGJ9YWF&psc=1&refRID=NRT85V0WZ9KWYXGJ9YWF) 24本 x 2箱 3,192‬円
　　<注文日(注文内容確定日)> 11/1(金)

イベント1週間前ぐらいまでひきつけて、11/10ごろに数決めて発注しましょう。今のところは懇親会でもこれを使って3箱づつを予定。

**Comment by aibax** [comment]
参加申込状況を考慮して
* 緑茶 24本 x 3箱
* 烏龍茶 24本 x 3箱
で発注完了
