### ISSUE TITLE
当日受付チーム担当

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#29]
手が回らなかったら、イベント会社手配してもいいよ。とおっしゃっていただけている。

**Comment by PharaohKJ** [comment]
ドアキを使ってのオペレーション・机配置含めて検討すること

**Comment by PharaohKJ** [comment]
ノベルティ（いまのところストラップ予定）を配布
写真NG登録の人など、登録枠に応じてストラップを配布すること

**Comment by PharaohKJ** [comment]
- [ ]  受付マニュアル作成

**Comment by PharaohKJ** [comment]
@osamu-036 さん
ここの wiki でも Google Docs でも Dropbox paper でもなんでもいいんで、当日みんなでスマホでみられる形で、ドアキでバーコード読むところ含めて受付マニュアルを作成してほしいです。

受付マニュアルは当日お手伝いいただくスタッフ（富山からいらっしゃる予定）によんでいただくためのもので、箇条書きで大丈夫かと思います。

その内容で人数なども決めていきたいと思います。よろしくおねがいします。
（いまのところ、10:00〜10：30は登壇スポンサー受付 3 & 一般受付 3 で 6、それいがいは1人ぐらいかなーと思っています。）

**Comment by osamu-036** [comment]
@PharaohKJ さん
了解です。週末までには、書いてみます。

**Comment by osamu-036** [comment]
すみません。仕事が炎上中で、ページは作ったものの、本のさわりしか書けておらず。。。

ちなみに、書き出して思ったのですが、登壇者や写真NGの方って、
どうストラップを区別するか決まってます？
（例えば、紐か名前を記入するカード(?)の色を分けるとか？）

https://github.com/jaws-ug-kanazawa/aws-community-day/wiki/WIP:%E5%BD%93%E6%97%A5%E5%8F%97%E4%BB%98%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB

**Comment by PharaohKJ** [comment]
https://drive.google.com/open?id=1TnvBJb6ud1KGyBMQgeIGBbGyFeVpYo3d
- 写真OKの方にはネイビー
- 写真NGの方にはホワイト
のストラップを配布してください。

登壇者受付、を隣に作成し、登壇者の場合には、普通の受付 & お名前をおうかがいして、対応するTシャツをお渡ししてください。

Tシャツのサイズ表は

https://docs.google.com/spreadsheets/d/1hSksqTIWz3XbIUhkyUZgb48nZkHr4g8jI-lMwLIhibw/edit?usp=sharing

を参照してください。この表、当日は印刷してもっていくようにします。

**Comment by PharaohKJ** [comment]
@osamu-036 さん↑よろしくです。

**Comment by osamu-036** [comment]
@PharaohKJ さん、すみません。遅くなりました。
とりあえず、思いつく限りは書いてみました。

https://github.com/jaws-ug-kanazawa/aws-community-day/wiki/%E5%BD%93%E6%97%A5%E5%8F%97%E4%BB%98%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB

**Comment by PharaohKJ** [comment]
@osamu-036 さん
だいたいOKだと思います。いろいろ追加したり省略したりしておきました。

ハンズオン受付は今週中に考えます。

**Comment by PharaohKJ** [comment]
@osamu-036 さん
飲酒に関してを案内に追加しました。
