### ISSUE TITLE
ハンズオン無線LAN貸し出し部

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#33]
#25 より派生。

- ITBP武蔵のSSIDとは別にする
- SSIDとパスワードを全く同じにする
- 干渉しないチャンネルにする ( 私の使ってるルータはチャンネル自動選択機能あり )

これSSIDとパスワード決めてルータに設定したらクローズ。

とりあえず SSID は handson 、パスワードは kanazawa2019 あたりにしておきましょうか？

**Comment by matyuda** [comment]
承知しました。

私の無線LANのアクセスポイントもチャネル自動選択機能があります。

中継器モードを利用しない＆情報コンセントが1つとのことですので、PharaohKJさんのアクセスポイントにハブがついているようでしたらイーサケーブルでアクセスポイント通しを繋ぐ方法とさせてください。

イーサネットケーブルは5メートルくらいしかないので、長いケーブルを調達する必要がありますね。

**Comment by PharaohKJ** [comment]
あの部屋をカバーするぐらいだから特に伸ばさなくても大丈夫だと思いますよ！

私のルータはハブ機能もあるんでそこにつなげましょう。

**Comment by yuuitiro** [comment]
通りすがりますけど、このモデルが弊社にごろっと（3台ほど）落ちてますが貸出できます。

https://www.buffalo.jp/product/detail/wapm-apg300n.html

**Comment by PharaohKJ** [comment]
@yuuitiro さん、当日2台ご用意いただいてよろしいですか？
バックアッププランとして使いたいです。オオゴトでしたら大丈夫です。
事前郵送が必要でしたら教えて下さい。

**Comment by PharaohKJ** [comment]
@yuuitiro さん

![ハンズオン回線図](https://user-images.githubusercontent.com/1581985/68517349-94b8a680-02ca-11ea-9123-4818f76ba92e.png)

このカタチにしようかなあと考えるんですがどうですかね？のべでいうと60人、会場では30〜35ぐらいの数なら同一SSIDでいけますかね？

**Comment by yuuitiro** [comment]
行けると思いますよ。
ロードバランシングの機能あるけど、つなぐSSID分けてもらえれば、確実ですね。

**Comment by PharaohKJ** [comment]
設定いつやりますかね？当日朝、私が設定できる？ @yuuitiro さん事前に設定していただけます？
それか当日お昼に入ってもらって即この作業に入ってもらうか、ですかねえ。
（これまでは、私と matyda さんそれぞれ自分の持ち込む予定だったので設定はそれぞれやってもらう予定だったのです）

**Comment by yuuitiro** [comment]
この程度なら事前設定してお渡しできますよ。
config は共有して「もしも」の時は対応お願いします！
多分最新機種よりトップスピード遅いけど、ルータを分けるので落ちずにそこそこ動いてくれると思います。

**Comment by PharaohKJ** [comment]
ありがとうございます。よろしくおねがいします。

**Comment by yuuitiro** [comment]
準備できました。

## ルータの設定

```
# show config
# RTX1200 Rev.10.01.53 (Mon Sep  9 15:23:58 2013)
# MAC Address : 00:a0:de:c0:7f:6b, 00:a0:de:c0:7f:6c, 00:a0:de:c0:7f:6d
# Memory 128Mbytes, 3LAN, 1BRI
# main:  RTX1200 ver=c0 serial=D26167067 MAC-Address=00:a0:de:c0:7f:6b MAC-Address=00:a0:de:c0:7f:6c MAC-Address=00:a0:de:c0:7f:6d
# Reporting Date: Nov 13 14:25:13 2019
console character ascii
ip lan1 address 192.168.100.1/24
ip lan2 address dhcp
ip lan2 nat descriptor 1
nat descriptor type 1 masquerade
nat descriptor address outer 1 primary
dhcp service server
dhcp server rfc2131 compliant except remain-silent
dhcp scope 1 192.168.100.2-192.168.100.191/24
```

## 無線LAN アクセスポイントの設定

### 1号機

ユーザ名 root
handson1
kanazawa2019

### 2号機

ユーザ名 root
handson1
kanazawa2019


## メモ
* 管理者用のパスワードは別便でお伝えします。
* 2019/11/14 相羽さんの会社に持って行きます。

**Comment by matyuda** [comment]
@PharaohKJ さん

私がもっていく予備のアクセスポイントは @yuuitiro さんにご用意いただいたアクセスポイントに合わせて SSID を handson1 としました。handson2 等への変更が必要であれば教えてください。

**Comment by PharaohKJ** [comment]
@matyuda さんのは
いまのところはバックアッププランなので、とりあえずそれでOKです。ありがとうございます。

**Comment by yuuitiro** [comment]
無線LANですが、RTX-1200 の LAN1 ポートにつなぐ場合はブリッジで、ITBPのLANポートにつなぐ場合はルータで接続すると良いです。

**Comment by PharaohKJ** [comment]
@yuuitiro さん、それは @matyuda さんのものを接続する場合ですよね？
その場合はLANポート直結しか考えてないです。ありがとうございます。
（性能的にハンズオン参加者向けには絶対ムリなんで、なにかあったときの疎通確認ぐらいを予定しています）

**Comment by yuuitiro** [comment]
そです、そです。
@matyuda さんのものを接続する場合です。ご存じかなとも思ったんですが、念のためコメントしておきましたー。

**Comment by PharaohKJ** [comment]
あざっす
-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pharaohkj / twitter: PhalanXware

**Comment by PharaohKJ** [comment]
こちらも @yuuitiro さんが @aibax さんより回収したらクローズ予定。マジで助かりました。ありがとうございました。

**Comment by TAKAyukiatkwsk** [comment]
@yuuitiro 
YAMAHAルータ素人の私でもLANケーブル繋げるだけで無線LAN利用できたので本当に助かりました！ありがとうございました！

**Comment by yuuitiro** [comment]
来週に回収したいと思いますー！

またハンズオンする機会があれば持ってきます :)

**Comment by yuuitiro** [comment]
@aibax さんから回収しました。

インフル疑惑があって回収が遅れましたが、無事OKです。
