### ISSUE TITLE
カニ食べたい人の数のアンケート

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#35]
https://github.com/jaws-ug-kanazawa/aws-community-day/issues/14#issuecomment-550837717

11/11(月)に、google formを作成して、その数を得ること。11/13に確定して #14 にフィードバックし @higachan0406 さん経由でお願いする。

目安としてカニ 2,000円いかないよね？その目安です、と別注希望確認とります。
参加人数、カニ人数確定したらクローズ予定。

**Comment by higachan0406** [comment]
今日、11/7(木)はカニ解禁でした。
今日の香箱蟹のお値段は初日だからでしょうか、「1,950円」とのことでした。
後、香箱蟹は取り置きができないようです。
なので、当日、シケなどで取れない場合は食べれません。もしくは数が少ないかも。
他店でも同様なのでお店回ってもありつけないとか。

**Comment by higachan0406** [comment]
1,950円は税込みか税抜か気になるなら聞いておきますが。

**Comment by PharaohKJ** [comment]
2,000円ぐらいと予想と書いておきます。

**Comment by PharaohKJ** [comment]
いったん締め切り。なんかあったら連絡します。
