### ISSUE TITLE
勉強会トラック配信テスト

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#36]
#23 より

機材を借りられたらトランザム吉田さんとテストにITBP武蔵にいく。

現在、機材貸出手配中。

**Comment by matyuda** [comment]
私も日程調整つけば同席させてください。

**Comment by PharaohKJ** [comment]
OK 日程決めるときは連絡します。

**Comment by PharaohKJ** [comment]
済み。問題がいくつかわかったのでレポートした。
レポートは[こちら](https://paper.dropbox.com/doc/--AoqxM_j1wVUttZDgRZ~kMOZdAQ-T1Pp5qvTujGCUbjE51W8y)

とりあえず準備はOKなので、当日おまかせする。
