### ISSUE TITLE
ハンズオン用電源タップ

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#37]
@jaws-ug-kanazawa/communityday 各位
30人いらっしゃるということで、割とガッツリ用意しないといけない。
貸していただける方はここに連絡ください。
ロジスティクス部のほうでまとめます。

**Comment by yuuitiro** [comment]
- 電源タップ (3p) 4個口 が ４つ ちょっと短い 2m かな
- 電源タップ (3p) ６個口 が ２つ
- 無線LANアクセスポイント（ルータ機能なし） が２つ
- ルータが必要であれば YAMAHA RTX-1200 が１つ
- ネットワークケーブル数本

以上提供可能です。

**Comment by yuuitiro** [comment]
来週金沢・福井へ出張る予定なので、そのときにおいていきますよ。
相羽さんの会社にお預けするのがいいのかな？

**Comment by PharaohKJ** [comment]
それがいちばん助かります。 @aibax さんと連絡とって進めてほしいですー。

ルータの設定については #33 でやりましょう！

**Comment by yuuitiro** [comment]
@aibax @PharaohKJ 当日はお昼ぐらいにそちらに付く予定なので、機材は事前にお渡し・あとから回収という流れにしたいと思っています。

12 or 14 に金沢方面へゆく予定があるので、そのときに機材をお渡しできればなーと。
回収はまだ予定未定です

**Comment by PharaohKJ** [comment]
@aibax さんより @yuuitiro さんが回収したらクローズ。ありがとうございました！

**Comment by TAKAyukiatkwsk** [comment]
@yuuitiro 
こちらも大変助かりました。ありがとうございました！

**Comment by yuuitiro** [comment]
来週の予定を考えてます。

@TAKAyukiatkwsk 役に立てたようでよかったっす！

**Comment by yuuitiro** [comment]
こちらも回収したのでクローズしておきます。
