### ISSUE TITLE
スタンドポップの返却

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#44]

**Comment by PharaohKJ** [comment]
スタンドポップをAWSさんに返却する。発送したらAWSさんに荷物番号伝えてクローズ。

**Comment by aibax** [comment]
11/22 有限会社キネ様宛にヤマト運輸にて発送完了
（伝票番号 : 4649-1306-3123）
↓
11/25 配達完了
