### ISSUE TITLE
会計報告

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#46]
@jaws-ug-kanazawa/communityday 各位、領収書の登録を wiki にしたがって進めて、なんとか24日いっぱいで終わらせてください。

残りは俺だけかな・・・？

**Comment by PharaohKJ** [comment]
@TAKAyukiatkwsk さん @matyuda さんへ 12/6 paypay 経由で 11,251 円清算しました。

**Comment by PharaohKJ** [comment]
@TAKAyukiatkwsk さん @higachan0406 さんへ 12/7 現金で 3,582 円精算しました。

**Comment by TAKAyukiatkwsk** [comment]
上記の精算、入金出金記録スプレッドシートの立て替えレコードに精算日を入力しておきました。

**Comment by PharaohKJ** [comment]
色分けわかりやすくて最高に助かります && 2シートめの入金・出金記録にも記入をお願いします。
2シート目の合計 = 1シート目の合計になることでちゃんとあってるかみたいと思います。
まぁいまの方法でも十分ですかね。

**Comment by TAKAyukiatkwsk** [comment]
> 2シート目の合計 = 1シート目の合計になることでちゃんとあってるかみたいと思います。

了解です！

**Comment by PharaohKJ** [comment]
@TAKAyukiatkwsk さん


12/9 に 9,576円 AWSさん（のイベント会社 KINEさん）に振り込み返金しました。

@aibax さんへ 12/12、 9,576円 + 吉田さんぶん 2,419円 合計 11,995円、Kyashで精算しました。

**Comment by PharaohKJ** [comment]
11/27 に AWSさん（のイベント会社 KINEさん）より 308,453円 **入金** がありました。
12/12 に @PharaohKJ が 272,049円 現金で精算しました。

**Comment by TAKAyukiatkwsk** [comment]
@PharaohKJ 
スプレッドシート更新しました。全ての立て替え精算が完了、入金・出金の合計値が0になることを確認しました。
https://docs.google.com/spreadsheets/d/1oy1TfvV6yV29Ml0JWFjyrmo_HYDNW1Huq9N8Jy6U7es/edit?usp=sharing
