### ISSUE TITLE
予算感作成

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#5]
- 箱が決まっているので、何人規模目標のイベントになるか
    - 会場費予約・見積もり(済) → AWS 支払い → 支払い期限
    - ノベルティ、お弁当などに影響大

**Comment by PharaohKJ** [comment]
https://docs.google.com/spreadsheets/d/1gKtcXLjpBnrprM_GlEcVV1R8Gghv_uzQZEjy7zUCd_k/edit?usp=sharing

どんなもんでしょう

**Comment by matyuda** [comment]
概ね大丈夫だと思います。
お弁当、懇親会の数は１００で足りるのでしょうか？
概算要求時には２割増しの１２０（スタッフが１５ということもありますし）でいかがでしょうか？

**Comment by PharaohKJ** [comment]
おーそうですね。ちょっと修正しておきます。

**Comment by PharaohKJ** [comment]
まぁいまのところOKもらってるのでいったんclose
