### ISSUE TITLE
飲み会領収書発行

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#50]
@higachan0406 さんPDFで領収書作成するので

欲しがってる人　と　その人の金額

のリストをこっそりslackのDMあたりで送ってください。

**Comment by higachan0406** [comment]
@PharaohKJ さん、
メモした紙は家にあるので後ほど連絡します。

**Comment by higachan0406** [comment]
@PharaohKJ さん
@aibax さん
Slackにて、加藤さんに状況を説明し、
相羽さんに作業を依頼しました。
本件については相羽さんの作業でクローズとしていただければ
よいかと思います。

**Comment by PharaohKJ** [comment]
PdF送ったり手渡ししたりしました。クローズ。
