### ISSUE TITLE
勉強会トラック部設置

### ISSUE THREAD

**Issue by PharaohKJ** [jaws-ug-kanazawa/aws-community-day#7]
- スポンサー/協賛企業への説明・募集開始（8月7日）3.5か月前　（少額でも稟議あるため早めに）
    - 会の主旨の説明資料作成（8月7日） 3.5か月前
- トラック表・タイムテーブルの作成
    - 登壇者オファーリスト作成（8月20日）3か月前
    - 全登壇者確定・タイトル・概要確定（11月7日) 2週間前
    - トラック数・セッション時間・枠数

**Comment by matyuda** [comment]
勉強会は、各JAWSUGとAmazon Chimeでオンラインで接続してやるのはどうでしょうか？
(Amazon Chimeの料金をAWSさんにご負担いただけない場合、Zoom等を使わない限り実現が難しいのだと思いますが。。。)

今年のAWS Community Dayの開催都市のサイト見てみると、日本で初めて開催するのが金沢だとすれば（非常に名誉なことであり）、それ（開催状況の共有とセッション内容を各UGと共有する目的で）を各地方のJAWSUGと共有する必要があるのではないかと思った次第です。

**Comment by PharaohKJ** [comment]
よいと思います。が、

- ちょっとハンズオン系も含めて回線問題(アップストリームがきつい)
- スライド+音声(映像もか)の配信はかなり難しい。
  - 投影しているスライドにフォーカスをあてると、コントラスト的に真っ暗になって登壇者の顔みえない
  - 登壇者にフォーカスをあてると、投影しているスライドが真っ白になってうつらない
  - そういうことを防ぐためにカメラや機材などのセットアップコストがめちゃくちゃ高い
  - わかってるサポートスタッフがたくさん必要

といった課題がみえています。このあたりクリアできればなんとかできるかなー。

ちょっと時間9/19とか10/5にテストしてみます？

**Comment by matyuda** [comment]
なるほど。
昨日CircleCIのWebinarがzoomであったのですが、この辺の部分が割と簡単に解決されていた感じがありました。
具体的には、登壇者のコンピュータのWebカメラとzoomによるデスクトップシェアリングによるスライド共有だったような感じがしています。
Amazon Chimeで同じことが出来るのかが分かりませんが、是非チャレンジしてみたいと思いますので、9/19 or 10/5 でテストしたいです。

アップストリームの問題と登壇者の方のWebカメラの件は課題かもしれませんね。。。

**Comment by TAKAyukiatkwsk** [comment]
回線は気になるところなのでテストしたいですね。。。(トラック並列2 + ハンズオン + 現地参加者の接続具合)

**Comment by matyuda** [comment]
ポスターやパンフレットに関係ある内容につき、一旦確認させてください。
トラック名ですが、
トラック１、トラック２　になりますか？
それとも　トラックA、トラックB　になりますか？

それともトラック利家、トラックまつ　など地元色出してみますか？

**Comment by PharaohKJ** [comment]
そのネタめっちゃいいけどトラックA、B、コマ数で連番としようかなと思ってました。


-- 
PhalanXware
Masayuki KaToH / kato@phalanxware.com
076-225-5965 / skype: pxw_kato / twitter: PhalanXware

**Comment by matyuda** [comment]
@PharaohKJ  さん
承知しました。A-1～　B-1～としておくことにします。

**Comment by PharaohKJ** [comment]
@PharaohKJ  登壇者オファー中 & 確定リストの作成

**Comment by matyuda** [comment]
- [ ] 配信機材一式の手配

1日あたり3万円程度での委託案あり

**Comment by PharaohKJ** [comment]
勉強会トラック配信部はちょっと別issueでやりましょう。

**Comment by PharaohKJ** [comment]
現状のオファーで、ランチセッションとアサイクルさまのところは調整中ですが、これでいったんいこうと思います。

レビューお願いします。

![スクリーンショット 2019-10-18 16 46 22](https://user-images.githubusercontent.com/1581985/67075867-ffdcf480-f1c6-11e9-8907-8f5d1cfc2fac.png)

**Comment by PharaohKJ** [comment]
@jaws-ug-kanazawa/communityday 

ハンズオン部屋、開場をランチセッションあとの13:30〜にしようと思います。

AWS亀田さんの食事する時間を確保したい by 私
開始には亀田さんがいたほうがよくない？と、亀田さんからご提案がありました。

どうでしょ？ 特に問題なければそうしようと思います。
